
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * 
 */
public class frmClase16 extends javax.swing.JDialog {

    frmClase16(JFrame jFrame, boolean b) {

        initComponents();
        
        this.setLocationRelativeTo(null); 
        
    }

    /**
     * Creates new form frmClase16
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        jPanelIngredientes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ingredienteNombre1 = new javax.swing.JTextField();
        ingredienteNombre2 = new javax.swing.JTextField();
        ingredienteNombre3 = new javax.swing.JTextField();
        ingredienteNombre4 = new javax.swing.JTextField();
        ingredienteNombre5 = new javax.swing.JTextField();
        ingredienteNombre6 = new javax.swing.JTextField();
        ingredienteNombre7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ingredienteNombre8 = new javax.swing.JTextField();
        ingredienteNombre9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ingredienteNombre10 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cantIngrediente1 = new javax.swing.JTextField();
        cantIngrediente2 = new javax.swing.JTextField();
        cantIngrediente3 = new javax.swing.JTextField();
        cantIngrediente4 = new javax.swing.JTextField();
        cantIngrediente5 = new javax.swing.JTextField();
        cantIngrediente6 = new javax.swing.JTextField();
        cantIngrediente7 = new javax.swing.JTextField();
        cantIngrediente8 = new javax.swing.JTextField();
        cantIngrediente9 = new javax.swing.JTextField();
        cantIngrediente10 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        costoIngrediente1 = new javax.swing.JTextField();
        costoIngrediente2 = new javax.swing.JTextField();
        costoIngrediente3 = new javax.swing.JTextField();
        costoIngrediente4 = new javax.swing.JTextField();
        costoIngrediente5 = new javax.swing.JTextField();
        costoIngrediente6 = new javax.swing.JTextField();
        costoIngrediente7 = new javax.swing.JTextField();
        costoIngrediente8 = new javax.swing.JTextField();
        costoIngrediente9 = new javax.swing.JTextField();
        costoIngrediente10 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        totalCantIngredientes = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        totalCostoIngredientes = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Catálogo de Productos");

        btnAceptar.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_calculator-512.png"))); // NOI18N
        btnAceptar.setText("Calcular");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jPanelIngredientes.setBorder(javax.swing.BorderFactory.createTitledBorder("Calculadora de Costos"));

        jLabel1.setText("Ingrediente 1: ");

        jLabel2.setText("Ingrediente 2: ");

        jLabel3.setText("Ingrediente 3: ");

        jLabel4.setText("Ingrediente 4: ");

        jLabel5.setText("Ingrediente 5: ");

        jLabel6.setText("Ingrediente 6: ");

        jLabel7.setText("Ingrediente 7: ");

        ingredienteNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredienteNombre1ActionPerformed(evt);
            }
        });

        ingredienteNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredienteNombre2ActionPerformed(evt);
            }
        });

        ingredienteNombre3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredienteNombre3ActionPerformed(evt);
            }
        });

        ingredienteNombre5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredienteNombre5ActionPerformed(evt);
            }
        });

        ingredienteNombre6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredienteNombre6ActionPerformed(evt);
            }
        });

        ingredienteNombre7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredienteNombre7ActionPerformed(evt);
            }
        });

        jLabel8.setText("Ingrediente 8: ");

        jLabel9.setText("Ingrediente 9: ");

        ingredienteNombre8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredienteNombre8ActionPerformed(evt);
            }
        });

        ingredienteNombre9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredienteNombre9ActionPerformed(evt);
            }
        });

        jLabel10.setText("Ingrediente 10: ");

        ingredienteNombre10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredienteNombre10ActionPerformed(evt);
            }
        });

        jLabel11.setText("Cantidad (kg):");

        jLabel12.setText("Cantidad (kg):");

        jLabel13.setText("Cantidad (kg):");

        jLabel14.setText("Cantidad (kg):");

        jLabel15.setText("Cantidad (kg):");

        jLabel16.setText("Cantidad (kg):");

        jLabel17.setText("Cantidad (kg):");

        jLabel18.setText("Cantidad (kg):");

        jLabel19.setText("Cantidad (kg):");

        jLabel20.setText("Cantidad (kg):");

        cantIngrediente1.setText("0");
        cantIngrediente1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cantIngrediente1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                cantIngrediente1CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        cantIngrediente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantIngrediente1ActionPerformed(evt);
            }
        });
        cantIngrediente1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantIngrediente1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantIngrediente1KeyTyped(evt);
            }
        });

        cantIngrediente2.setText("0");
        cantIngrediente2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cantIngrediente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantIngrediente2ActionPerformed(evt);
            }
        });

        cantIngrediente3.setText("0");
        cantIngrediente3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cantIngrediente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantIngrediente3ActionPerformed(evt);
            }
        });

        cantIngrediente4.setText("0");
        cantIngrediente4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        cantIngrediente5.setText("0");
        cantIngrediente5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cantIngrediente5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantIngrediente5ActionPerformed(evt);
            }
        });

        cantIngrediente6.setText("0");
        cantIngrediente6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        cantIngrediente7.setText("0");
        cantIngrediente7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        cantIngrediente8.setText("0");
        cantIngrediente8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        cantIngrediente9.setText("0");
        cantIngrediente9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        cantIngrediente10.setText("0");
        cantIngrediente10.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cantIngrediente10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantIngrediente10ActionPerformed(evt);
            }
        });

        jLabel21.setText("Costo $:");

        jLabel22.setText("Costo $:");

        jLabel23.setText("Costo $:");

        jLabel24.setText("Costo $:");

        jLabel25.setText("Costo $:");

        jLabel26.setText("Costo $:");

        jLabel27.setText("Costo $:");

        jLabel28.setText("Costo $:");

        jLabel29.setText("Costo $:");

        jLabel30.setText("Costo $:");

        costoIngrediente1.setText("0");
        costoIngrediente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costoIngrediente1ActionPerformed(evt);
            }
        });
        costoIngrediente1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                costoIngrediente1KeyTyped(evt);
            }
        });

        costoIngrediente2.setText("0");
        costoIngrediente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costoIngrediente2ActionPerformed(evt);
            }
        });

        costoIngrediente3.setText("0");

        costoIngrediente4.setText("0");

        costoIngrediente5.setText("0");
        costoIngrediente5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costoIngrediente5ActionPerformed(evt);
            }
        });

        costoIngrediente6.setText("0");
        costoIngrediente6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costoIngrediente6ActionPerformed(evt);
            }
        });

        costoIngrediente7.setText("0");

        costoIngrediente8.setText("0");

        costoIngrediente9.setText("0");
        costoIngrediente9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costoIngrediente9ActionPerformed(evt);
            }
        });

        costoIngrediente10.setText("0");

        jLabel31.setText("Total (kg):");

        totalCantIngredientes.setText("0");
        totalCantIngredientes.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        totalCantIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalCantIngredientesActionPerformed(evt);
            }
        });

        jLabel32.setText("Total $:");

        totalCostoIngredientes.setText("0");

        javax.swing.GroupLayout jPanelIngredientesLayout = new javax.swing.GroupLayout(jPanelIngredientes);
        jPanelIngredientes.setLayout(jPanelIngredientesLayout);
        jPanelIngredientesLayout.setHorizontalGroup(
            jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIngredientesLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelIngredientesLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(ingredienteNombre10, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelIngredientesLayout.createSequentialGroup()
                        .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(24, 24, 24)
                        .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ingredienteNombre4)
                            .addComponent(ingredienteNombre2)
                            .addComponent(ingredienteNombre3)
                            .addGroup(jPanelIngredientesLayout.createSequentialGroup()
                                .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ingredienteNombre1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(ingredienteNombre5)
                                    .addComponent(ingredienteNombre6)
                                    .addComponent(ingredienteNombre7)
                                    .addComponent(ingredienteNombre8)
                                    .addComponent(ingredienteNombre9))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(54, 54, 54)
                .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelIngredientesLayout.createSequentialGroup()
                        .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIngredientesLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(27, 27, 27)))
                .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cantIngrediente6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantIngrediente7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelIngredientesLayout.createSequentialGroup()
                        .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cantIngrediente1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantIngrediente2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantIngrediente3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantIngrediente4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantIngrediente5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantIngrediente8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantIngrediente9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantIngrediente10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalCantIngredientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelIngredientesLayout.createSequentialGroup()
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(costoIngrediente10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelIngredientesLayout.createSequentialGroup()
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(costoIngrediente9, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelIngredientesLayout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(costoIngrediente8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelIngredientesLayout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(costoIngrediente7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelIngredientesLayout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(costoIngrediente6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelIngredientesLayout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(costoIngrediente5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelIngredientesLayout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(costoIngrediente4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelIngredientesLayout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(costoIngrediente3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelIngredientesLayout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(costoIngrediente2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelIngredientesLayout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(costoIngrediente1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelIngredientesLayout.createSequentialGroup()
                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalCostoIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(41, 41, 41))
        );
        jPanelIngredientesLayout.setVerticalGroup(
            jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIngredientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelIngredientesLayout.createSequentialGroup()
                        .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cantIngrediente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(costoIngrediente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(cantIngrediente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(cantIngrediente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(cantIngrediente4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(cantIngrediente5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(cantIngrediente6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(cantIngrediente7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cantIngrediente8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(cantIngrediente9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(cantIngrediente10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelIngredientesLayout.createSequentialGroup()
                        .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(ingredienteNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(costoIngrediente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(ingredienteNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ingredienteNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(costoIngrediente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ingredienteNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)
                            .addComponent(costoIngrediente4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(ingredienteNombre5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(costoIngrediente5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ingredienteNombre6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(costoIngrediente6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ingredienteNombre7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel27)
                                .addComponent(costoIngrediente7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ingredienteNombre8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)
                            .addComponent(costoIngrediente8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(ingredienteNombre9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)
                            .addComponent(costoIngrediente9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(ingredienteNombre10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30)
                            .addComponent(costoIngrediente10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(48, 48, 48)
                .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel31)
                    .addGroup(jPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(totalCantIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel32)
                        .addComponent(totalCostoIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelIngredientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(361, 361, 361)
                .addComponent(btnAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jPanelIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

    BigDecimal valor1 = new BigDecimal("0");
        valor1 = valor1.add(new BigDecimal(costoIngrediente1.getText())); 
        valor1 = valor1.add(new BigDecimal(costoIngrediente2.getText()));
        valor1 = valor1.add(new BigDecimal(costoIngrediente3.getText()));
        valor1 = valor1.add(new BigDecimal(costoIngrediente4.getText()));
        valor1 = valor1.add(new BigDecimal(costoIngrediente5.getText()));
        valor1 = valor1.add(new BigDecimal(costoIngrediente6.getText()));
        valor1 = valor1.add(new BigDecimal(costoIngrediente7.getText()));
        valor1 = valor1.add(new BigDecimal(costoIngrediente8.getText()));
        valor1 = valor1.add(new BigDecimal(costoIngrediente9.getText()));
        valor1 = valor1.add(new BigDecimal(costoIngrediente10.getText()));
        
    BigDecimal valor2 = new BigDecimal("0");
    valor2 = valor2.add(new BigDecimal(cantIngrediente1.getText()));
    valor2 = valor2.add(new BigDecimal(cantIngrediente2.getText()));
    valor2 = valor2.add(new BigDecimal(cantIngrediente3.getText()));
    valor2 = valor2.add(new BigDecimal(cantIngrediente4.getText()));
    valor2 = valor2.add(new BigDecimal(cantIngrediente5.getText()));
    valor2 = valor2.add(new BigDecimal(cantIngrediente6.getText()));
    valor2 = valor2.add(new BigDecimal(cantIngrediente7.getText()));
    valor2 = valor2.add(new BigDecimal(cantIngrediente8.getText()));
    valor2 = valor2.add(new BigDecimal(cantIngrediente9.getText()));
    valor2 = valor2.add(new BigDecimal(cantIngrediente10.getText()));
     
      this.totalCostoIngredientes.setText(valor1.toString());
      this.totalCantIngredientes.setText(valor2.toString());
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void ingredienteNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredienteNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingredienteNombre1ActionPerformed

    private void ingredienteNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredienteNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingredienteNombre2ActionPerformed

    private void ingredienteNombre3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredienteNombre3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingredienteNombre3ActionPerformed

    private void ingredienteNombre5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredienteNombre5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingredienteNombre5ActionPerformed

    private void ingredienteNombre6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredienteNombre6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingredienteNombre6ActionPerformed

    private void ingredienteNombre7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredienteNombre7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingredienteNombre7ActionPerformed

    private void ingredienteNombre8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredienteNombre8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingredienteNombre8ActionPerformed

    private void ingredienteNombre9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredienteNombre9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingredienteNombre9ActionPerformed

    private void ingredienteNombre10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredienteNombre10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingredienteNombre10ActionPerformed

    private void totalCantIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalCantIngredientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalCantIngredientesActionPerformed

    private void cantIngrediente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantIngrediente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantIngrediente2ActionPerformed

    private void cantIngrediente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantIngrediente3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantIngrediente3ActionPerformed

    private void cantIngrediente5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantIngrediente5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantIngrediente5ActionPerformed

    private void cantIngrediente10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantIngrediente10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantIngrediente10ActionPerformed

    private void costoIngrediente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costoIngrediente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costoIngrediente2ActionPerformed

    private void costoIngrediente5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costoIngrediente5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costoIngrediente5ActionPerformed

    private void costoIngrediente6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costoIngrediente6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costoIngrediente6ActionPerformed

    private void costoIngrediente9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costoIngrediente9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costoIngrediente9ActionPerformed

    private void cantIngrediente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantIngrediente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantIngrediente1ActionPerformed

    private void cantIngrediente1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantIngrediente1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantIngrediente1KeyPressed

    private void cantIngrediente1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cantIngrediente1CaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cantIngrediente1CaretPositionChanged

    private void cantIngrediente1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantIngrediente1KeyTyped
        char vChar = evt.getKeyChar();
                    if (!(Character.isDigit(vChar)
                            || (vChar == KeyEvent.VK_BACK_SPACE)
                            || (vChar == KeyEvent.VK_DELETE)
                            || (vChar == KeyEvent.VK_PERIOD))) {
                        evt.consume();
                    }
    }//GEN-LAST:event_cantIngrediente1KeyTyped

    private void costoIngrediente1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costoIngrediente1KeyTyped
                char vChar = evt.getKeyChar();
                    if (!(Character.isDigit(vChar)
                            || (vChar == KeyEvent.VK_BACK_SPACE)
                            || (vChar == KeyEvent.VK_DELETE)
                            || (vChar == KeyEvent.VK_PERIOD))) {
                        evt.consume();
                    }
    }//GEN-LAST:event_costoIngrediente1KeyTyped

    private void costoIngrediente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costoIngrediente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costoIngrediente1ActionPerformed
    private void costoIngrediente2KeyTyped(java.awt.event.KeyEvent evt) {                                           
                char vChar = evt.getKeyChar();
                    if (!(Character.isDigit(vChar)
                            || (vChar == KeyEvent.VK_BACK_SPACE)
                            || (vChar == KeyEvent.VK_DELETE)
                            || (vChar == KeyEvent.VK_PERIOD))) {
                        evt.consume();
                    }
    } 
        private void costoIngrediente3KeyTyped(java.awt.event.KeyEvent evt) {                                           
                char vChar = evt.getKeyChar();
                    if (!(Character.isDigit(vChar)
                            || (vChar == KeyEvent.VK_BACK_SPACE)
                            || (vChar == KeyEvent.VK_DELETE)
                            || (vChar == KeyEvent.VK_PERIOD))) {
                        evt.consume();
                    }
    } 
        
    private void costoIngrediente4KeyTyped(java.awt.event.KeyEvent evt) {                                           
                char vChar = evt.getKeyChar();
                    if (!(Character.isDigit(vChar)
                            || (vChar == KeyEvent.VK_BACK_SPACE)
                            || (vChar == KeyEvent.VK_DELETE)
                            || (vChar == KeyEvent.VK_PERIOD))) {
                        evt.consume();
                    }
    } 
    
    private void costoIngrediente5KeyTyped(java.awt.event.KeyEvent evt) {                                           
                char vChar = evt.getKeyChar();
                    if (!(Character.isDigit(vChar)
                            || (vChar == KeyEvent.VK_BACK_SPACE)
                            || (vChar == KeyEvent.VK_DELETE)
                            || (vChar == KeyEvent.VK_PERIOD))) {
                        evt.consume();
                    }
    } 
    
    
    private void costoIngrediente6KeyTyped(java.awt.event.KeyEvent evt) {                                           
                char vChar = evt.getKeyChar();
                    if (!(Character.isDigit(vChar)
                            || (vChar == KeyEvent.VK_BACK_SPACE)
                            || (vChar == KeyEvent.VK_DELETE)
                            || (vChar == KeyEvent.VK_PERIOD))) {
                        evt.consume();
                    }
    }
    private void costoIngrediente7KeyTyped(java.awt.event.KeyEvent evt) {                                           
                char vChar = evt.getKeyChar();
                    if (!(Character.isDigit(vChar)
                            || (vChar == KeyEvent.VK_BACK_SPACE)
                            || (vChar == KeyEvent.VK_DELETE)
                            || (vChar == KeyEvent.VK_PERIOD))) {
                        evt.consume();
                    }
    } 
    
    
    private void costoIngrediente8KeyTyped(java.awt.event.KeyEvent evt) {                                           
                char vChar = evt.getKeyChar();
                    if (!(Character.isDigit(vChar)
                            || (vChar == KeyEvent.VK_BACK_SPACE)
                            || (vChar == KeyEvent.VK_DELETE)
                            || (vChar == KeyEvent.VK_PERIOD))) {
                        evt.consume();
                    }
    } 
    private void costoIngrediente9KeyTyped(java.awt.event.KeyEvent evt) {                                           
                char vChar = evt.getKeyChar();
                    if (!(Character.isDigit(vChar)
                            || (vChar == KeyEvent.VK_BACK_SPACE)
                            || (vChar == KeyEvent.VK_DELETE)
                            || (vChar == KeyEvent.VK_PERIOD))) {
                        evt.consume();
                    }
    } 
    
    
    private void costoIngrediente10KeyTyped(java.awt.event.KeyEvent evt) {                                           
                char vChar = evt.getKeyChar();
                    if (!(Character.isDigit(vChar)
                            || (vChar == KeyEvent.VK_BACK_SPACE)
                            || (vChar == KeyEvent.VK_DELETE)
                            || (vChar == KeyEvent.VK_PERIOD))) {
                        evt.consume();
                    }
    }     
    
 
    private void cantIngrediente2KeyTyped(java.awt.event.KeyEvent evt) {                                          
        char vChar = evt.getKeyChar();
                    if (!(Character.isDigit(vChar)
                            || (vChar == KeyEvent.VK_BACK_SPACE)
                            || (vChar == KeyEvent.VK_DELETE)
                            || (vChar == KeyEvent.VK_PERIOD))) {
                        evt.consume();
                    }
    }  
    private void cantIngrediente3KeyTyped(java.awt.event.KeyEvent evt) {                                          
        char vChar = evt.getKeyChar();
                    if (!(Character.isDigit(vChar)
                            || (vChar == KeyEvent.VK_BACK_SPACE)
                            || (vChar == KeyEvent.VK_DELETE)
                            || (vChar == KeyEvent.VK_PERIOD))) {
                        evt.consume();
                    }
    }     
    
   
    private void cantIngrediente4KeyTyped(java.awt.event.KeyEvent evt) {                                          
        char vChar = evt.getKeyChar();
                    if (!(Character.isDigit(vChar)
                            || (vChar == KeyEvent.VK_BACK_SPACE)
                            || (vChar == KeyEvent.VK_DELETE)
                            || (vChar == KeyEvent.VK_PERIOD))) {
                        evt.consume();
                    }
    }  

        private void cantIngrediente5KeyTyped(java.awt.event.KeyEvent evt) {                                          
        char vChar = evt.getKeyChar();
                    if (!(Character.isDigit(vChar)
                            || (vChar == KeyEvent.VK_BACK_SPACE)
                            || (vChar == KeyEvent.VK_DELETE)
                            || (vChar == KeyEvent.VK_PERIOD))) {
                        evt.consume();
                    }
    }  
        
        
         private void cantIngrediente6KeyTyped(java.awt.event.KeyEvent evt) {                                          
        char vChar = evt.getKeyChar();
                    if (!(Character.isDigit(vChar)
                            || (vChar == KeyEvent.VK_BACK_SPACE)
                            || (vChar == KeyEvent.VK_DELETE)
                            || (vChar == KeyEvent.VK_PERIOD))) {
                        evt.consume();
                    }
    }     
         
       private void cantIngrediente7KeyTyped(java.awt.event.KeyEvent evt) {                                          
        char vChar = evt.getKeyChar();
                    if (!(Character.isDigit(vChar)
                            || (vChar == KeyEvent.VK_BACK_SPACE)
                            || (vChar == KeyEvent.VK_DELETE)
                            || (vChar == KeyEvent.VK_PERIOD))) {
                        evt.consume();
                    }
    }  
       
       
    private void cantIngrediente8KeyTyped(java.awt.event.KeyEvent evt) {                                          
        char vChar = evt.getKeyChar();
                    if (!(Character.isDigit(vChar)
                            || (vChar == KeyEvent.VK_BACK_SPACE)
                            || (vChar == KeyEvent.VK_DELETE)
                            || (vChar == KeyEvent.VK_PERIOD))) {
                        evt.consume();
                    }
    }     
       
    
        private void cantIngrediente9KeyTyped(java.awt.event.KeyEvent evt) {                                          
        char vChar = evt.getKeyChar();
                    if (!(Character.isDigit(vChar)
                            || (vChar == KeyEvent.VK_BACK_SPACE)
                            || (vChar == KeyEvent.VK_DELETE)
                            || (vChar == KeyEvent.VK_PERIOD))) {
                        evt.consume();
                    }
    }  
        
        
    private void cantIngrediente10KeyTyped(java.awt.event.KeyEvent evt) {                                          
        char vChar = evt.getKeyChar();
                    if (!(Character.isDigit(vChar)
                            || (vChar == KeyEvent.VK_BACK_SPACE)
                            || (vChar == KeyEvent.VK_DELETE)
                            || (vChar == KeyEvent.VK_PERIOD))) {
                        evt.consume();
                    }
    }
       
    // Setter para asiganar código

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmClase16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmClase16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmClase16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmClase16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                frmClase16 dialog = new frmClase16(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JTextField cantIngrediente1;
    private javax.swing.JTextField cantIngrediente10;
    private javax.swing.JTextField cantIngrediente2;
    private javax.swing.JTextField cantIngrediente3;
    private javax.swing.JTextField cantIngrediente4;
    private javax.swing.JTextField cantIngrediente5;
    private javax.swing.JTextField cantIngrediente6;
    private javax.swing.JTextField cantIngrediente7;
    private javax.swing.JTextField cantIngrediente8;
    private javax.swing.JTextField cantIngrediente9;
    private javax.swing.JTextField costoIngrediente1;
    private javax.swing.JTextField costoIngrediente10;
    private javax.swing.JTextField costoIngrediente2;
    private javax.swing.JTextField costoIngrediente3;
    private javax.swing.JTextField costoIngrediente4;
    private javax.swing.JTextField costoIngrediente5;
    private javax.swing.JTextField costoIngrediente6;
    private javax.swing.JTextField costoIngrediente7;
    private javax.swing.JTextField costoIngrediente8;
    private javax.swing.JTextField costoIngrediente9;
    private javax.swing.JTextField ingredienteNombre1;
    private javax.swing.JTextField ingredienteNombre10;
    private javax.swing.JTextField ingredienteNombre2;
    private javax.swing.JTextField ingredienteNombre3;
    private javax.swing.JTextField ingredienteNombre4;
    private javax.swing.JTextField ingredienteNombre5;
    private javax.swing.JTextField ingredienteNombre6;
    private javax.swing.JTextField ingredienteNombre7;
    private javax.swing.JTextField ingredienteNombre8;
    private javax.swing.JTextField ingredienteNombre9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelIngredientes;
    private javax.swing.JTextField totalCantIngredientes;
    private javax.swing.JTextField totalCostoIngredientes;
    // End of variables declaration//GEN-END:variables
}
