
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @
 */
public class frmClase07b extends javax.swing.JDialog {

    /**
     * Creates new form frmClase07b
     */
    // Declaro variable de Conexion
    clsConnection oConn = new clsConnection();
    
    // Variable para las funciones propias
    clsFunciones  oFunc = new clsFunciones();
    
    
    
    public frmClase07b(java.awt.Frame parent, boolean modal) 
    {
        // Código de Inicialización
        super(parent, modal);
        initComponents();
        
        //Centro la Forma   
        this.setLocationRelativeTo(null);
        
         // deshabilita resize
       // this.setResizable(false);
        
               
        
        // Carga el combo de Medidas
        //sbCargaMedidas();
        
        // Se alinea a la derecha los campos numéricos
       // txtInicial.setHorizontalAlignment(JTextField.LEFT);
        txtPrecio2.setHorizontalAlignment(JTextField.LEFT);
        txtPrecio3.setHorizontalAlignment(JTextField.LEFT);
        txtPrecio4.setHorizontalAlignment(JTextField.LEFT);
        txtPrecio5.setHorizontalAlignment(JTextField.LEFT);
        txtPrecio6.setHorizontalAlignment(JTextField.LEFT);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDetalle = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblInicial = new javax.swing.JLabel();
        lblEntradas = new javax.swing.JLabel();
        lblSalidas = new javax.swing.JLabel();
        lblActual = new javax.swing.JLabel();
        lblCosto = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtInicial = new javax.swing.JTextField();
        txtPrecio5 = new javax.swing.JTextField();
        txtPrecio6 = new javax.swing.JTextField();
        lblIcoCodigo = new javax.swing.JLabel();
        lblIcoNombre = new javax.swing.JLabel();
        lblIcoDescripcion = new javax.swing.JLabel();
        lblIcoMedida = new javax.swing.JLabel();
        lblIcoInicial = new javax.swing.JLabel();
        lblIcoCosto = new javax.swing.JLabel();
        lblIcoPrecio = new javax.swing.JLabel();
        txtPrecio2 = new javax.swing.JTextField();
        txtPrecio1 = new javax.swing.JTextField();
        txtPrecio4 = new javax.swing.JTextField();
        txtPrecio3 = new javax.swing.JTextField();
        txtPrecio7 = new javax.swing.JTextField();
        lblPrecio1 = new javax.swing.JLabel();
        txtPrecio8 = new javax.swing.JTextField();
        lblPrecio2 = new javax.swing.JLabel();
        txtPrecio9 = new javax.swing.JTextField();
        lblPrecio3 = new javax.swing.JLabel();
        txtPrecio10 = new javax.swing.JTextField();
        lblPrecio4 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Catálogo de Productos");

        pnlDetalle.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información del Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 0, 12))); // NOI18N

        lblCodigo.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblCodigo.setText("Código:");

        lblNombre.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblNombre.setText("Nombre:");

        lblDescripcion.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblDescripcion.setText("Descripcion:");

        lblInicial.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblInicial.setText("Precio 1:");

        lblEntradas.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblEntradas.setText("Precio 2:");

        lblSalidas.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblSalidas.setText("Precio 3:");

        lblActual.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblActual.setText("Precio 4:");

        lblCosto.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblCosto.setText("Precio 5:");

        lblPrecio.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblPrecio.setText("Precio 6:");

        txtCodigo.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtCodigo.setMaximumSize(new java.awt.Dimension(170, 25));
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtNombre.setMaximumSize(new java.awt.Dimension(170, 25));

        txtDescripcion.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtDescripcion.setMaximumSize(new java.awt.Dimension(170, 25));
        txtDescripcion.setPreferredSize(new java.awt.Dimension(170, 21));

        txtInicial.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtInicial.setText("0");
        txtInicial.setMaximumSize(new java.awt.Dimension(170, 21));
        txtInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInicialActionPerformed(evt);
            }
        });

        txtPrecio5.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtPrecio5.setText("0");
        txtPrecio5.setMaximumSize(new java.awt.Dimension(170, 21));
        txtPrecio5.setPreferredSize(new java.awt.Dimension(170, 21));

        txtPrecio6.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtPrecio6.setText("0");
        txtPrecio6.setMaximumSize(new java.awt.Dimension(170, 21));

        lblIcoCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihelp.png"))); // NOI18N
        lblIcoCodigo.setToolTipText("13 Caracteres oara el Código");

        lblIcoNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihelp.png"))); // NOI18N
        lblIcoNombre.setToolTipText("20 Caracteres para el Nombre");

        lblIcoDescripcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihelp.png"))); // NOI18N
        lblIcoDescripcion.setToolTipText("50 Caracteres para la Descripción");

        lblIcoMedida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihelp.png"))); // NOI18N
        lblIcoMedida.setToolTipText("5 Caracteres para la Medida");

        lblIcoInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihelp.png"))); // NOI18N

        lblIcoCosto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihelp.png"))); // NOI18N
        lblIcoCosto.setToolTipText("Costo del Producto mayor que 0");

        lblIcoPrecio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihelp.png"))); // NOI18N
        lblIcoPrecio.setToolTipText("Precio del Producto mayor que 0");

        txtPrecio2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtPrecio2.setText("0");
        txtPrecio2.setMaximumSize(new java.awt.Dimension(170, 21));
        txtPrecio2.setPreferredSize(new java.awt.Dimension(170, 21));

        txtPrecio1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtPrecio1.setText("0");
        txtPrecio1.setMaximumSize(new java.awt.Dimension(170, 21));

        txtPrecio4.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtPrecio4.setText("0");
        txtPrecio4.setMaximumSize(new java.awt.Dimension(170, 21));
        txtPrecio4.setPreferredSize(new java.awt.Dimension(170, 21));

        txtPrecio3.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtPrecio3.setText("0");
        txtPrecio3.setMaximumSize(new java.awt.Dimension(170, 21));
        txtPrecio3.setPreferredSize(new java.awt.Dimension(170, 21));

        txtPrecio7.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtPrecio7.setText("0");
        txtPrecio7.setMaximumSize(new java.awt.Dimension(170, 21));

        lblPrecio1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblPrecio1.setText("Precio 7:");

        txtPrecio8.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtPrecio8.setText("0");
        txtPrecio8.setMaximumSize(new java.awt.Dimension(170, 21));

        lblPrecio2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblPrecio2.setText("Precio 8:");

        txtPrecio9.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtPrecio9.setText("0");
        txtPrecio9.setMaximumSize(new java.awt.Dimension(170, 21));

        lblPrecio3.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblPrecio3.setText("Precio 9:");

        txtPrecio10.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtPrecio10.setText("0");
        txtPrecio10.setMaximumSize(new java.awt.Dimension(170, 21));

        lblPrecio4.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblPrecio4.setText("Precio 10:");

        javax.swing.GroupLayout pnlDetalleLayout = new javax.swing.GroupLayout(pnlDetalle);
        pnlDetalle.setLayout(pnlDetalleLayout);
        pnlDetalleLayout.setHorizontalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(lblInicial)
                    .addComponent(lblCosto)
                    .addComponent(lblCodigo)
                    .addComponent(lblDescripcion)
                    .addComponent(lblPrecio)
                    .addComponent(lblEntradas)
                    .addComponent(lblSalidas)
                    .addComponent(lblActual)
                    .addComponent(lblPrecio1)
                    .addComponent(lblPrecio2)
                    .addComponent(lblPrecio3)
                    .addComponent(lblPrecio4))
                .addGap(10, 10, 10)
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPrecio9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtInicial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPrecio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPrecio2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPrecio3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPrecio4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPrecio5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPrecio6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPrecio7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPrecio8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPrecio10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIcoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIcoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIcoCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIcoMedida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblIcoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblIcoPrecio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIcoDescripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlDetalleLayout.setVerticalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDetalleLayout.createSequentialGroup()
                        .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblIcoCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCodigo, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre)
                            .addComponent(lblIcoNombre))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblDescripcion))
                            .addComponent(lblIcoDescripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE))
                    .addGroup(pnlDetalleLayout.createSequentialGroup()
                        .addComponent(txtPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)))
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDetalleLayout.createSequentialGroup()
                        .addComponent(lblIcoMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblIcoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblIcoCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDetalleLayout.createSequentialGroup()
                        .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInicial))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEntradas))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSalidas))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPrecio4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblActual))
                    .addComponent(lblIcoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCosto)
                    .addComponent(txtPrecio5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecio))
                .addGap(18, 18, 18)
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecio1))
                .addGap(18, 18, 18)
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecio2))
                .addGap(18, 18, 18)
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecio3))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecio4))
                .addContainerGap())
        );

        btnAceptar.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aceptar.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private boolean fnBoolDatosCorrectos()
    {
        // Variable de Resultado
        boolean bResultado=true;
        int iValor;
        String sValor;
        javax.swing.ImageIcon oIconoAceptar = new javax.swing.ImageIcon(getClass().getResource("/aceptar.png"));
        javax.swing.ImageIcon oIconoCancelar = new javax.swing.ImageIcon(getClass().getResource("/cancelar.png"));
        
        
        // Valida el Código
        if (txtCodigo.getText().trim().isEmpty() || txtCodigo.getText().trim().length()> 15 )
        {    
            lblIcoCodigo.setIcon(oIconoCancelar);
            bResultado = false;
        }
        else
            lblIcoCodigo.setIcon(oIconoAceptar);
        
        // Valida el Nombre
        if (txtNombre.getText().trim().isEmpty() || txtNombre.getText().trim().length()> 20 )
        {    
            lblIcoNombre.setIcon(oIconoCancelar);
            bResultado = false;
        }
        else
            // Hace visible su ícono correspondiente
            lblIcoNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aceptar.png")));
        
        // Valida la Descripción
        if (txtDescripcion.getText().trim().isEmpty() || txtDescripcion.getText().trim().length()> 50 )
        {    
            lblIcoDescripcion.setIcon(oIconoCancelar);
            bResultado = false;
        }
        else
            lblIcoDescripcion.setIcon(oIconoAceptar);
        
        // Valida la Existencia Inicial
        sValor = txtInicial.getText().toString();      
        if (! oFunc.fnBoolIsInteger(sValor))        
        {    
            lblIcoInicial.setIcon(oIconoCancelar);
            bResultado = false;
        }
        else
            if (Integer.valueOf(sValor)<=0)
            {
                lblIcoInicial.setIcon(oIconoCancelar);
                bResultado = false;
            }
            else
                lblIcoInicial.setIcon(oIconoAceptar);
        
        // Valida el Costo
        sValor = txtPrecio5.getText().toString();      
        if (! oFunc.fnBoolIsDecimal(sValor))        
        {    
            lblIcoCosto.setIcon(oIconoCancelar);
            bResultado = false;
        }
        else
             if(Double.valueOf(sValor) <= 0)
             {
                lblIcoCosto.setIcon(oIconoCancelar);
                bResultado = false;
             }
            else
                lblIcoCosto.setIcon(oIconoAceptar);
        
        // Valida el Precio
        sValor = txtPrecio6.getText().toString();      
        if (! oFunc.fnBoolIsDecimal(sValor))        
        {    
            lblIcoPrecio.setIcon(oIconoCancelar);
            bResultado = false;
        }
        else
             if(Double.valueOf(sValor)<=0)
             {
                lblIcoPrecio.setIcon(oIconoCancelar);
                bResultado = false;
             }
            else
                lblIcoPrecio.setIcon(oIconoAceptar);
               
        
        
        // retorna el Resultado
        return bResultado;
    }
    
    public boolean fnBoolProductoExiste(boolean bDisplay)
    {
        // Para devolver el resultado
        boolean bResultado=false;
        
        // Para el Query
        String sQuery;
        
        // Prepara el Query
        sQuery  = "Select * from 04tblProductos Where strProductoCodigo='"+txtCodigo.getText()+"'";
        
        //Ejecuta el Query
        oConn.FnBoolQueryExecute(sQuery);
        
        // Capturo el Error
        try {
            // Verifico que haya habido resultados
            if (oConn.setResult.next())
            {
        
                // Verifica si debe desplegar
                if (bDisplay)
                {
                    // Obtengo los datos
                    txtNombre.setText(oConn.setResult.getString("strProductoCodigo"));
                    txtNombre.setText(oConn.setResult.getString("strProductoNombre"));
                    txtDescripcion.setText(oConn.setResult.getString("strProductoDescripcion"));
                    txtInicial.setText(oConn.setResult.getString("decProductoPrecio1"));
                    txtPrecio2.setText(oConn.setResult.getString("decProductoPrecio2"));
                    txtPrecio3.setText(oConn.setResult.getString("decProductoPrecio3"));
                    txtPrecio4.setText(oConn.setResult.getString("decProductoPrecio4"));
                    txtPrecio5.setText(oConn.setResult.getString("decProductoPrecio5"));
                    txtPrecio6.setText(oConn.setResult.getString("decProductoPrecio6"));
                    txtPrecio7.setText(oConn.setResult.getString("decProductoPrecio7"));
                    txtPrecio8.setText(oConn.setResult.getString("decProductoPrecio8"));
                    txtPrecio9.setText(oConn.setResult.getString("decProductoPrecio9"));
                    txtPrecio10.setText(oConn.setResult.getString("decProductoPrecio10"));
                }
                // Resultado
                bResultado = true;

            }
            
            // Cierro los Resultados
            oConn.setResult.close();
                
        } catch (SQLException ex) {
            oFunc.SubSistemaMensaje("fnBoolProductoExiste:"+ex.getMessage().toString());
        }
        
        
        
        // Retorna el Resultado
        return bResultado;
        
    }
    
    // Procedimiento para insertar el producto
    private void sbInsertaProducto()
    {
        String sQuery;
        
        // Prepara el Query para Insertar
        sQuery = "Insert into 04tblProductos Values (";
        sQuery += "'"+txtCodigo.getText().toString()+"',";
        sQuery += "'"+txtNombre.getText().toString()+"',";
        sQuery += "'"+txtDescripcion.getText().toString()+"',";
        sQuery += txtPrecio1.getText().toString()+",";
        sQuery += txtPrecio2.getText().toString()+",";
        sQuery += txtPrecio3.getText().toString()+",";
        sQuery += txtPrecio4.getText().toString()+",";
        sQuery += txtPrecio5.getText().toString()+",";
        sQuery += txtPrecio6.getText().toString()+",";
        sQuery += txtPrecio7.getText().toString()+",";
        sQuery += txtPrecio8.getText().toString()+",";
        sQuery += txtPrecio9.getText().toString()+",";        
        sQuery += txtPrecio10.getText().toString()+")";
        
        // Para ver el Query
        //oFunc.SubSistemaMensaje(sQuery);
                
                
                        
        // Ejecuta la Insercion
        if (oConn.FnBoolQueryExecuteUpdate(sQuery))
            oFunc.SubSistemaMensaje("La Inserción se ha realizado con éxito");
        
        // Cierra la Forma
        this.dispose();
        
    }
    
    private void sbModificaProducto()
    {
        
        // Variable para el Query
        String sQuery;
               
        // Prepara el Query para modificar
        sQuery = " Update 04tblProductos Set ";
        sQuery += " strProductoNombre='"+txtNombre.getText().toString()+"',";
        sQuery += " strProductoDescripcion='"+txtDescripcion.getText().toString()+"',";
        sQuery += " decProductoPrecio1="+txtPrecio1.getText()+",";
        sQuery += " decProductoPrecio2="+txtPrecio2.getText()+",";
        sQuery += " decProductoPrecio3="+txtPrecio3.getText()+",";
        sQuery += " decProductoPrecio4="+txtPrecio4.getText()+",";
        sQuery += " decProductoPrecio5="+txtPrecio5.getText()+",";
        sQuery += " decProductoPrecio6="+txtPrecio6.getText()+",";
        sQuery += " decProductoPrecio7="+txtPrecio7.getText()+",";
        sQuery += " decProductoPrecio8="+txtPrecio8.getText()+",";
        sQuery += " decProductoPrecio9="+txtPrecio9.getText()+",";
        sQuery += " decProductoPrecio10="+txtPrecio10.getText();
        sQuery += " Where strProductoCodigo='"+txtCodigo.getText()+"'";
        
        // Para ver el Query
        //oFunc.SubSistemaMensaje(sQuery);
                        
        // Ejecuta la Insercion
        if (oConn.FnBoolQueryExecuteUpdate(sQuery))
            oFunc.SubSistemaMensaje("La Modificación se ha realizado con éxito");
        
        // Cierra la Forma
        this.dispose();
        
    }
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        if (this.getTitle().toString().lastIndexOf("Insertar")>=0)
        {
            if (fnBoolProductoExiste(true))
                oFunc.SubSistemaMensaje("El Código de Producto YA existe");
            else
                if (fnBoolDatosCorrectos())
                   sbInsertaProducto();
        }
        else
            if (! fnBoolProductoExiste(false))
                oFunc.SubSistemaMensaje("El Código de Producto NO existe");
            else
                if (fnBoolDatosCorrectos())
                   sbModificaProducto();
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        // TODO add your handling code here:

        if (this.getTitle().toString().lastIndexOf("Editar")>=0)
        evt.consume();
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed
        if (this.getTitle().toString().lastIndexOf("Editar")>=0)
        evt.consume();
    }//GEN-LAST:event_txtCodigoKeyPressed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInicialActionPerformed

    private void sbCargaMedidas()
    {
        // Variable para el Query
        String sQuery;
        
        // Prepara el Query
        sQuery ="Select distinct(strProductoMedida) from 04tblProductos";
        
        if (oConn.FnBoolQueryExecute(sQuery))
        {
            try 
            {
                // Verifica resultados
                 while (oConn.setResult.next())
                 {                     
                     // Obtiene los datos de la Consulta
                    // cboMedida.addItem(oConn.setResult.getString ("strProductoMedida"));
                     
                 }
                 
                 // Cierra Resultados
                 oConn.setResult.close();
            } 
            catch (SQLException ex) 
            {
                //JOptionPane.showMessageDialorootPane,ex);
                oFunc.SubSistemaMensaje(ex.toString());
                Logger.getLogger(frmClase05.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        // Desselecciona
      // cboMedida.setSelectedIndex(-1);
    }
    
    private void setJTexFieldChanged(JTextField txt)
    {
        // Crear una variable para 
        DocumentListener documentListener = new DocumentListener() 
        {

            @Override
            public void changedUpdate(DocumentEvent documentEvent) {
                //oFunc.SubSistemaMensaje("Update");
                printIt(documentEvent);
            }

            @Override
            public void insertUpdate(DocumentEvent documentEvent) {
                //oFunc.SubSistemaMensaje("Insert");
                printIt(documentEvent);
            }

            @Override
            public void removeUpdate(DocumentEvent documentEvent) {
                //oFunc.SubSistemaMensaje("Remove");
                printIt(documentEvent);
            }
        };
        
        // Agregamos el capturador de evento del objeto
        txt.getDocument().addDocumentListener(documentListener);

    }
     
    private void printIt(DocumentEvent documentEvent) 
    {
    
        // Definir una variable de tipo de eentos
        DocumentEvent.EventType type = documentEvent.getType();

        if (type.equals(DocumentEvent.EventType.CHANGE))
        {
            oFunc.SubSistemaMensaje("Change");
             txtEjemploJTextFieldChanged();
        }
        else if (type.equals(DocumentEvent.EventType.INSERT))
        {
             txtEjemploJTextFieldChanged();

        }
        else if (type.equals(DocumentEvent.EventType.REMOVE))
        {
            txtEjemploJTextFieldChanged();

        }
    }
    private void txtEjemploJTextFieldChanged()
    {
        int iSuma;
        int iInicial;
        int iEntradas;
        int iSalidas;
        
        //if (txtInicial.getText().isEmpty())
        if (! oFunc.fnBoolIsInteger(txtInicial.getText()))    
            this.txtPrecio4.setText("Error");
        else
        {
            // Obtengo los datoa
            iInicial = Integer.valueOf(txtInicial.getText());
            iEntradas = Integer.valueOf(txtPrecio2.getText());
            iSalidas = Integer.valueOf(txtPrecio3.getText());
            iSuma = iInicial+iEntradas-iSalidas;
            //Copiar el contenido del jtextfield al jlabel
            this.txtPrecio4.setText(String.valueOf(iSuma));
            
        }
      
    }
    
    // Setter para asiganar código
    public void setCodigo(String sCodigo)
    {
        // Coloco el Código
        txtCodigo.setText(sCodigo);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmClase07b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmClase07b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmClase07b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmClase07b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                frmClase07b dialog = new frmClase07b(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblActual;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEntradas;
    private javax.swing.JLabel lblIcoCodigo;
    private javax.swing.JLabel lblIcoCosto;
    private javax.swing.JLabel lblIcoDescripcion;
    private javax.swing.JLabel lblIcoInicial;
    private javax.swing.JLabel lblIcoMedida;
    private javax.swing.JLabel lblIcoNombre;
    private javax.swing.JLabel lblIcoPrecio;
    private javax.swing.JLabel lblInicial;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecio1;
    private javax.swing.JLabel lblPrecio2;
    private javax.swing.JLabel lblPrecio3;
    private javax.swing.JLabel lblPrecio4;
    private javax.swing.JLabel lblSalidas;
    private javax.swing.JPanel pnlDetalle;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtInicial;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio1;
    private javax.swing.JTextField txtPrecio10;
    private javax.swing.JTextField txtPrecio2;
    private javax.swing.JTextField txtPrecio3;
    private javax.swing.JTextField txtPrecio4;
    private javax.swing.JTextField txtPrecio5;
    private javax.swing.JTextField txtPrecio6;
    private javax.swing.JTextField txtPrecio7;
    private javax.swing.JTextField txtPrecio8;
    private javax.swing.JTextField txtPrecio9;
    // End of variables declaration//GEN-END:variables
}
