
import java.sql.SQLException;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @
 */
public class frmClase14 extends javax.swing.JDialog {

    /**
     * Creates new form frmClase14
     */
    // Variable para las funciones propias
    clsFunciones  oFunc = new clsFunciones();
    clsConnection oConn = new clsConnection();
    
    public frmClase14(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         
        //Centro la Forma   
        this.setLocationRelativeTo(null);
        
        // Carga los Parametros
        sbCargaParametros();
    }
    
    private void sbCargaParametros()
    {
        // Declara una la variable
        String sQuery;
        
        // Prepara el Query
        sQuery ="Select * from 07tblparametros";
                
        //Ejecuta el Query
        oConn.FnBoolQueryExecute(sQuery);
        
        // Capturo el Error
        try {
            
            // Verifico que haya habido resultados
            if (oConn.setResult.next())
            {
        
                // Obtiene si agrupa productos
                if  (oConn.setResult.getInt("intAgruparProductos")==1)
                    chkAgrupar.setSelected(true);
                else
                    chkAgrupar.setSelected(false);
                
                // Obtiene si vende sin existencias
                if  (oConn.setResult.getInt("intVerificarExistencias")==1)
                    chkExistencias.setSelected(true);
                else
                    chkExistencias.setSelected(false);

                // Obtiene si vende sin existencias
                if  (oConn.setResult.getInt("intMensajesExito")==1)
                    chkMensajes.setSelected(true);
                else
                    chkMensajes.setSelected(false);
                
                // Obtiene si esta activa la bitacora
                if  (oConn.setResult.getInt("intBitacoraActiva")==1)
                    chkBitacora.setSelected(true);
                else
                    chkBitacora.setSelected(false);
                
                // Obtiene si vende sin existencias
                txtTicket.setText(oConn.setResult.getString("strTicketInfoFinal"));
                    

            }
        } catch (SQLException ex) {
            oFunc.SubSistemaMensaje("sbCargaParametrosos:"+ex.getMessage().toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        chkMensajes = new javax.swing.JCheckBox();
        chkExistencias = new javax.swing.JCheckBox();
        chkAgrupar = new javax.swing.JCheckBox();
        txtTicket = new javax.swing.JTextField();
        lblTicket = new javax.swing.JLabel();
        chkBitacora = new javax.swing.JCheckBox();
        butAccept = new javax.swing.JButton();
        butCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Parámetros del Sistema");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        chkMensajes.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        chkMensajes.setText("Desplegar Mensajes de Éxito");

        chkExistencias.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        chkExistencias.setText("Verificar Existencias en Venta");

        chkAgrupar.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        chkAgrupar.setText("Agrupar Productos Similares en Venta");

        lblTicket.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        lblTicket.setText("Texto del Ticket");

        chkBitacora.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        chkBitacora.setText("Bitacora Activa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chkAgrupar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkExistencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkMensajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTicket)
                    .addComponent(lblTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkBitacora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(chkMensajes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkExistencias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkAgrupar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkBitacora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(lblTicket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        butAccept.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        butAccept.setText("Accept");
        butAccept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butAcceptMouseClicked(evt);
            }
        });
        butAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAcceptActionPerformed(evt);
            }
        });

        butCancel.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        butCancel.setText("Cancel");
        butCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butCancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butAccept))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butCancel)
                    .addComponent(butAccept))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butAcceptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butAcceptMouseClicked
        // TODO add your handling code here:      

        // Declaro variable para Sentencia
        String sqlStmt;
        String sDato;

        // Prepara Variable para realizar el Query
        sqlStmt = "  Update 07tblparametros Set ";    
        sDato = chkExistencias.isSelected() ? "1" : "0";
        sqlStmt += " intVerificarExistencias=" + sDato+ ",";
        sDato = chkAgrupar.isSelected() ? "1" : "0";
        sqlStmt += " intAgruparProductos=" + sDato+",";
        sDato = chkMensajes.isSelected() ? "1" : "0";
        sqlStmt += " intMensajesExito=" + sDato+",";
        sDato = chkBitacora.isSelected() ? "1" : "0";
        sqlStmt += " intBitacoraActiva=" + sDato+",";
        sqlStmt += " strTicketInfoFinal='" + txtTicket.getText()+"'";
        
        
        // Ejecuto la Consulta
        oConn.FnBoolQueryExecuteUpdate(sqlStmt);
        
        // Cierra la VEntana
        this.dispose();
        
    }//GEN-LAST:event_butAcceptMouseClicked

    
    private void butAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAcceptActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_butAcceptActionPerformed

    private void butCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butCancelMouseClicked
        // TODO add your handling code here:                
        //JOptionPane.showMessageDialog(null,"Press Cancel");
        this.dispose();
    }//GEN-LAST:event_butCancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmClase14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmClase14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmClase14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmClase14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                frmClase14 dialog = new frmClase14(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAccept;
    private javax.swing.JButton butCancel;
    private javax.swing.JCheckBox chkAgrupar;
    private javax.swing.JCheckBox chkBitacora;
    private javax.swing.JCheckBox chkExistencias;
    private javax.swing.JCheckBox chkMensajes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTicket;
    private javax.swing.JTextField txtTicket;
    // End of variables declaration//GEN-END:variables
}
