import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Clase02.java
 *
 * Created on 25/05/2011, 02:43:42 PM
 */
/**
 *
 * @author jaor
 */

public class frmClase03 extends javax.swing.JFrame {
   
    // Declaro variable de Conexion
    clsConnection oConn = new clsConnection();
        
    /** Creates new form Clase02 */
    public frmClase03() {
        // Declaro variable de Conexion
        
        // Intento Conexcion        
        if (! oConn.FnBoolConnectionOpen("com.mysql.jdbc.Driver", "jdbc:mysql://localhost/test", "root", "portal01"))
        {
            // No Funciona una vez visible
            // this.dispose(); 
            
            // Mensaje de que no logrola conexion
            JOptionPane.showMessageDialog(null,"No se logro la conexion al Host");
            
            // Finaliza la Aplicación
            System.exit(0);
            
        }
        else
        {
            // Inicializa Componentes
            initComponents();   



            //Centro la Forma   
            this.setLocationRelativeTo(null);        
            this.setTitle("Begin Session");
            this.setResizable(false);


            //Inicializa Controles
            lblUser.setText("User:");
            lblPassword.setText("Password:");
            txtUser.setText("");
            txpPassword.setText("");
            butCancel.setText("Cancel");
            butAccept.setText("Accept");
            
            // Deshabilita los despliegues
            lblName.setText("Name:");
            lblRole.setText("Role:");
            txtName.setEnabled(false);
            txtName.setBackground(Color.DARK_GRAY);
            txtRole.setEnabled(false);
            txtRole.setBackground(Color.DARK_GRAY);
        }
        
        
    }
        

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSession = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txpPassword = new javax.swing.JPasswordField();
        lblName = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtRole = new javax.swing.JTextField();
        butAccept = new javax.swing.JButton();
        butCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName(""); // NOI18N

        pnlSession.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnlSession.setName(""); // NOI18N

        lblUser.setText("jLabel1");
        lblUser.setName(""); // NOI18N

        lblPassword.setText("jLabel2");
        lblPassword.setName("lblPassword"); // NOI18N

        txtUser.setName("txtUser"); // NOI18N

        txpPassword.setName("txpPassword"); // NOI18N

        lblName.setText("jLabel3");
        lblName.setName("lblName"); // NOI18N

        lblRole.setText("jLabel4");
        lblRole.setName("lblRole"); // NOI18N

        txtName.setName("txtName"); // NOI18N

        txtRole.setName("txtRole"); // NOI18N

        javax.swing.GroupLayout pnlSessionLayout = new javax.swing.GroupLayout(pnlSession);
        pnlSession.setLayout(pnlSessionLayout);
        pnlSessionLayout.setHorizontalGroup(
            pnlSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSessionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassword)
                    .addComponent(lblName)
                    .addComponent(lblUser)
                    .addComponent(lblRole))
                .addGap(43, 43, 43)
                .addGroup(pnlSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(txtRole, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(txpPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(txtUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlSessionLayout.setVerticalGroup(
            pnlSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSessionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPassword)
                    .addComponent(txpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pnlSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRole))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblUser.getAccessibleContext().setAccessibleName("");
        lblPassword.getAccessibleContext().setAccessibleName("lblPassword");
        txtUser.getAccessibleContext().setAccessibleName("txtUser");

        butAccept.setText("jButton1");
        butAccept.setName("butAccept"); // NOI18N
        butAccept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butAcceptMouseClicked(evt);
            }
        });

        butCancel.setText("jButton2");
        butCancel.setName("butCancel"); // NOI18N
        butCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butCancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(butCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butAccept))
                    .addComponent(pnlSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butAccept)
                    .addComponent(butCancel))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnlSession.getAccessibleContext().setAccessibleDescription("Sesion");
        butAccept.getAccessibleContext().setAccessibleName("butAceptar");
        butCancel.getAccessibleContext().setAccessibleName("butCancelar");

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butCancelMouseClicked
        // TODO add your handling code here:                
        //JOptionPane.showMessageDialog(null,"Press Cancel");
        this.dispose();
    }//GEN-LAST:event_butCancelMouseClicked

    private void butAcceptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butAcceptMouseClicked
        // TODO add your handling code here:      
        
        // Declaro variable para Sentencia
        String sqlStmt;
        
        // Verifico que esté intentando ingresar
        if (butAccept.getText()=="Accept")
        {
           
            // Prepara Variable para realizar el Query
            sqlStmt = "Select * from tblusers";
            sqlStmt += " Where strUserIde='"+txtUser.getText()+"'";
            sqlStmt += " And   strUserPass='"+String.valueOf(txpPassword.getPassword()) +"'";

            // Capturo el Error
            try 
            {
                // Ejecuto la Consulta
                if (oConn.FnBoolQueryExecute(sqlStmt))            
                {    

                    // Verifico que haya habido resultados
                    if (oConn.setResult.next())
                    {
                        //oConn.setResult.first();
                        //System.out.println ("Col 1:"+oConn.setResult.getString (1)); 
                        txtName.setText(oConn.setResult.getString ("strUserName"));
                        txtRole.setText(oConn.setResult.getString ("strRoleName"));

                        //Cambio el Texto del Boton
                        butAccept.setText("Sig in");
                        //Deshabilito Cancelar
                        butCancel.setEnabled(false);
                    }
                    else
                    {
                        txtName.setText("User & Password Incorrect");
                        txtRole.setText("Try again ...");
                    }

                    // Cierra la Consulta
                    oConn.setResult.close();
                }

            } 
            catch (RuntimeException e)
            {
                 // Mensaje de que no logrola conexion
                 JOptionPane.showMessageDialog(null,"Este Mensaje"+e);

            }
            catch (com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException e)
            {
                 // Mensaje de que no logrola conexion
                 JOptionPane.showMessageDialog(null,"Este Mensaje"+e);

            }
            catch (SQLException ex) 
            {                                
                Logger.getLogger(frmClase03.class.getName()).log(Level.SEVERE, null, ex);
            }

           
        
        }
        else
        {
            // Bievenido
            JOptionPane.showMessageDialog(null, "Ingresando al Sistema");
        }
    }//GEN-LAST:event_butAcceptMouseClicked
    
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmClase03().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAccept;
    private javax.swing.JButton butCancel;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlSession;
    private javax.swing.JPasswordField txpPassword;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRole;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
