
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmClase05.java
 *
 * Created on 11/11/2019, 09:29:15 AM
 */
/**
 *
 * @author jaor
 */
public class frmClase21 extends javax.swing.JDialog {

    // Declaro variable de Conexion
    clsConnection oConn = new clsConnection();
    
    // Declaro variable 
    String strCveActual;
    
    /** Creates new form frmClase05 */
    public frmClase21(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // Centra la Forma
        this.setLocationRelativeTo(null);
        
            
        // Carga el ListBox con los procesos
        SubProcesoCarga();
        
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlProcesos = new javax.swing.JPanel();
        butGrabar = new javax.swing.JButton();
        txtNombrePuerto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema-Procesos");

        pnlProcesos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Puerto Serie", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 0, 12))); // NOI18N
        pnlProcesos.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        pnlProcesos.setName("pnlProcesos"); // NOI18N

        butGrabar.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        butGrabar.setText("Aceptar");
        butGrabar.setName("butGrabar"); // NOI18N
        butGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butGrabarActionPerformed(evt);
            }
        });

        txtNombrePuerto.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtNombrePuerto.setName("txtNombrePuerto"); // NOI18N
        txtNombrePuerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePuertoActionPerformed(evt);
            }
        });
        txtNombrePuerto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombrePuertoKeyPressed(evt);
            }
        });

        jLabel1.setText("Puerto:");
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout pnlProcesosLayout = new javax.swing.GroupLayout(pnlProcesos);
        pnlProcesos.setLayout(pnlProcesosLayout);
        pnlProcesosLayout.setHorizontalGroup(
            pnlProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProcesosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtNombrePuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(pnlProcesosLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(butGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlProcesosLayout.setVerticalGroup(
            pnlProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProcesosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombrePuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(butGrabar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(pnlProcesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlProcesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlProcesos.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void txtNombrePuertoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombrePuertoKeyPressed
// TODO add your handling code here:
    
}//GEN-LAST:event_txtNombrePuertoKeyPressed

private void butGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butGrabarActionPerformed

    // TODO add your handling code here:
    String strSqlStmt;
    
    
    // Valida los datos correctos
    if (FnBoolValidaDatos())
    {
        // Prepara el Query
        strSqlStmt  = " Update 15tblConfigPuertoSerial ";
        strSqlStmt += " Set strPuerto='"+txtNombrePuerto.getText()+"'";
 

        // Ejecuta el Query
        oConn.FnBoolQueryExecuteUpdate(strSqlStmt);

        // Carga los Procesos de Nueva Cuenta
        
        this.dispose();
       // SubProcesosCarga();
    
    }
}//GEN-LAST:event_butGrabarActionPerformed

    private void txtNombrePuertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePuertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePuertoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmClase05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmClase05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmClase05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmClase05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                frmClase05 dialog = new frmClase05(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                
               
            }
        });
    }
   
    // Carga el puerto existentes a la lista
    private void SubProcesoCarga()
    {
        // Para instrucción sql
        String sqlStmt;
        String strPuerto = "";
        
         // Prepara Variable para realizar el Query
        sqlStmt = "Select * from 15tblConfigPuertoSerial";
        
        if (oConn.FnBoolQueryExecute(sqlStmt))
        {
            try 
            {
                // Verifica resultados
                 while (oConn.setResult.next())
                 {
                     // Obtiene los datos de la Consulta
                     strPuerto = oConn.setResult.getString ("strPuerto");
                 }                 
                  
                 txtNombrePuerto.setText(strPuerto);
                 
                 
                 
                 // Cierra Resultados
                 oConn.setResult.close();
            } 
            catch (SQLException ex) 
            {
                JOptionPane.showMessageDialog(rootPane,ex);
                Logger.getLogger(frmClase05.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }
    
    // Valida que los datos sean capturador
    boolean FnBoolValidaDatos()
    {
        // Variable para el Mensaje
        String strMensaje="";
        
        // Valida el Ide
        if (txtNombrePuerto.getText().length()==0 )
        {
           strMensaje = "Debe completar el nombre del puerto serie.";
           txtNombrePuerto.requestFocus();
        }
                
        // Valida si faltaron datos
        if (strMensaje.length()>0)
        {
            // Construye el Mensaje
            strMensaje ="Debe ingresar los siguientes datos:\n"+strMensaje;
            
            // Muestra el Mensaje
            JOptionPane.showMessageDialog(this, strMensaje);
            
            // Retorna
            return false;
            
        }
        else
            
            return true;
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butGrabar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlProcesos;
    private javax.swing.JTextField txtNombrePuerto;
    // End of variables declaration//GEN-END:variables
}
