
import java.sql.SQLException;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @
 */
public class frmClase09b extends javax.swing.JDialog {

      clsFunciones  oFunc = new clsFunciones();
      clsConnection oConn = new clsConnection();
    /**
     * Creates new form frmClase09b
     */
    public frmClase09b(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // Manda el foco a recibir
        txtRecibida.requestFocus();
         
        // deshabilita resize
        this.setResizable(false);
        
         // Centra la Forma
        this.setLocationRelativeTo(null);
        
        // Obtiene el total de la venta
        lblCobrarView.setText(clsGlobales.sTotalVenta.replace(",", "."));
        sbSetearClientes();
        
    }
    
    private void sbCalculaCambio()
    {
        double douPagar;
        double douRecibida;
        double  douCambio;
        
        if (! lblCobrarView.getText().isEmpty() && ! txtRecibida.getText().isEmpty())
        {

            // Obtengo la Cantidad a Pagar
            douPagar = Float.valueOf(lblCobrarView.getText());

            // Obtengo la Cantidad Recibida
            douRecibida = Float.valueOf(txtRecibida.getText());

            // Calculo la diferencia hasta que sea mayor o igual la cantidad recibida
            if (douRecibida >= douPagar)
            {
                // Calculo el Cambio
                douCambio = douRecibida-douPagar;

                // Coloca el cambio
                if (douCambio>9)
                   lblCambioView.setText(String.format("%5.2f",douCambio));            
                else
                   lblCambioView.setText(String.format("%1.2f",douCambio));             
                
            }
            else
                // Coloca el cambio en 0
                lblCambioView.setText("0.00");            
                
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFormaPago = new javax.swing.JLabel();
        lblCobrar = new javax.swing.JLabel();
        lblRecibida = new javax.swing.JLabel();
        lblCambio = new javax.swing.JLabel();
        lblReferencia = new javax.swing.JLabel();
        cboFormaPago = new javax.swing.JComboBox();
        lblCobrarView = new javax.swing.JLabel();
        lblCambioView = new javax.swing.JLabel();
        txtRecibida = new javax.swing.JTextField();
        txtReferencia = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblCambioEnLetras = new javax.swing.JLabel();
        lblFormaPago1 = new javax.swing.JLabel();
        C = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cobro de Venta");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblFormaPago.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblFormaPago.setText("Forma de Pago:");

        lblCobrar.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblCobrar.setText("Cantidad a Cobrar:");

        lblRecibida.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblRecibida.setText("Cantidad Recibida:");

        lblCambio.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblCambio.setText("Cambio:");

        lblReferencia.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblReferencia.setText("Saldo:");

        cboFormaPago.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        cboFormaPago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cuenta Corriente", "Efectivo" }));
        cboFormaPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFormaPagoActionPerformed(evt);
            }
        });

        lblCobrarView.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblCobrarView.setForeground(new java.awt.Color(51, 51, 255));
        lblCobrarView.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCobrarView.setText("0");
        lblCobrarView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblCobrarView.setMaximumSize(new java.awt.Dimension(4, 4));
        lblCobrarView.setMinimumSize(new java.awt.Dimension(4, 4));

        lblCambioView.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblCambioView.setForeground(new java.awt.Color(51, 51, 255));
        lblCambioView.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCambioView.setText("0.00");
        lblCambioView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblCambioView.setMaximumSize(new java.awt.Dimension(4, 4));
        lblCambioView.setMinimumSize(new java.awt.Dimension(4, 4));
        lblCambioView.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblCambioViewPropertyChange(evt);
            }
        });

        txtRecibida.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        txtRecibida.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRecibida.setText("0");
        txtRecibida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecibidaActionPerformed(evt);
            }
        });
        txtRecibida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRecibidaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRecibidaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRecibidaKeyTyped(evt);
            }
        });

        txtReferencia.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        txtReferencia.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtReferencia.setEnabled(false);

        btnAceptar.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aceptar_venta.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setMaximumSize(new java.awt.Dimension(135, 57));
        btnAceptar.setMinimumSize(new java.awt.Dimension(135, 57));
        btnAceptar.setPreferredSize(new java.awt.Dimension(135, 57));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancelado_1.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblCambioEnLetras.setFont(new java.awt.Font("Lucida Sans", 0, 10)); // NOI18N
        lblCambioEnLetras.setForeground(new java.awt.Color(51, 51, 255));
        lblCambioEnLetras.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCambioEnLetras.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblFormaPago1.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblFormaPago1.setText("Cliente:");

        C.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(212, 212, 212))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCambioEnLetras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblFormaPago1)
                                .addGap(110, 110, 110)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCobrarView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCambioView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboFormaPago, javax.swing.GroupLayout.Alignment.TRAILING, 0, 330, Short.MAX_VALUE)
                                    .addComponent(txtRecibida)
                                    .addComponent(C, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtReferencia)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFormaPago)
                            .addComponent(lblCobrar)
                            .addComponent(lblRecibida))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFormaPago1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 14, Short.MAX_VALUE)
                        .addComponent(lblFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 14, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRecibida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRecibida, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addComponent(lblCambio))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCobrarView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(lblCambioView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCambioEnLetras, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        // Acepta la Venta
        clsGlobales.bVentaRealizada=false;
        
        // Cierra la Forma
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void sbSetearClientes(){
        String sQuery = "";
        sQuery = "Select * from 12tblClientes";

        //Ejecuta el Query
        oConn.FnBoolQueryExecute(sQuery);
        
        // Capturo el Error
        try {

            // Verifico que haya habido resultados
            while (oConn.setResult.next())
            {
        
                // Obtengo los datos en el Objeto combo
                C.addItem(oConn.setResult.getString("intClienteCodigo") + " - " + oConn.setResult.getString("strClienteNombre") + " " + oConn.setResult.getString("strClienteApellido") );
                System.err.println(oConn.setResult.getString("intClienteCodigo") + " - " + oConn.setResult.getString("strClienteNombre") + " " + oConn.setResult.getString("strClienteApellido") );
            }
            
        // Cierro los Resultados
        oConn.setResult.close();
                
        } catch (SQLException ex) {
            oFunc.SubSistemaMensaje("sbSetearClientes:"+ex.getMessage().toString());
        }
    }
    
    private boolean fnBoolCobroCorrecto()
    {
        // Variable para el resultado
        boolean bResult = true;
        
          sbCalculaCambio();
        return bResult;
    }
    
    
    
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        
        // Si el cobro está correcto
        if (fnBoolCobroCorrecto())
        {
            // Acepta la Venta
            clsGlobales.bVentaRealizada=true;
            
            // Forma de Pago
            clsGlobales.sFormaPago=cboFormaPago.getSelectedItem().toString();
            clsGlobales.sReferencia = txtReferencia.getText();
            clsGlobales.codCliente= String.valueOf(C.getSelectedItem());
            clsGlobales.cantRecibida= txtRecibida.getText().replace(",", ".");
            clsGlobales.vuelto = lblCambioView.getText().replace(",", ".");
            
             // Cierra la Forma
             this.dispose();
        }
        
       
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtRecibidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRecibidaKeyTyped
        // TODO add your handling code here:
        
        if ((int)evt.getKeyChar()<48 || (int)evt.getKeyChar()>57)
            if ((int)evt.getKeyChar()==46)
            {
                if (txtRecibida.getText().lastIndexOf(".")>=0)
                    evt.consume();
                    
            }
            else
                evt.consume();
    }//GEN-LAST:event_txtRecibidaKeyTyped

    private void txtRecibidaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRecibidaKeyReleased

        // TODO add your handling code here:
        sbCalculaCambio();
    }//GEN-LAST:event_txtRecibidaKeyReleased

    private void cboFormaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFormaPagoActionPerformed

    }//GEN-LAST:event_cboFormaPagoActionPerformed

    private void lblCambioViewPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblCambioViewPropertyChange
        // TODO add your handling code here:
        String sEntero;
        String sDecimal;
        int iLongitud;
        int iEntero;
        
        // Obtengo la Longitud
        iLongitud = lblCambioView.getText().length();
        
        // Obtengo la parte entera
        sEntero = lblCambioView.getText().substring(0,iLongitud-3);
        iEntero = Integer.valueOf(sEntero);
        
        // Obtengo la parte decimal
        sDecimal = lblCambioView.getText().substring(iLongitud-2)+"/100.";
        lblCambioEnLetras.setText(oFunc.getStringOfNumber(iEntero)+ " PESOS "+sDecimal);

    }//GEN-LAST:event_lblCambioViewPropertyChange

    private void txtRecibidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecibidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecibidaActionPerformed

    private void txtRecibidaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRecibidaKeyPressed
                // TODO add your handling code here:
                sbCalculaCambio();
                
                traerSaldo();
    }//GEN-LAST:event_txtRecibidaKeyPressed

    private void traerSaldo(){
       // if (lblCobrarView.getText().equals("")){    
            String sQuery = "";
            //sQuery = "Select * from 12tblClientes";
            String codCliente = C.getSelectedItem().toString();
            String substring = codCliente.substring(0,2);
            sQuery = "select decSaldo from 13tbldetallectacte where intClienteCodigo = " + substring.trim();   

            //Ejecuta el Query
            oConn.FnBoolQueryExecute(sQuery);

            // Capturo el Error
            try {
                // Verifico que haya habido resultados
                while (oConn.setResult.next())
                {
                    // Obtengo los datos en el Objeto combo
                    txtReferencia.setText(oConn.setResult.getString("decSaldo")  );
                }
            // Cierro los Resultados
            oConn.setResult.close();

            } catch (SQLException ex) {
                oFunc.SubSistemaMensaje("sbSetearClientes:"+ex.getMessage().toString());
            }
        //}
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmClase09b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmClase09b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmClase09b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmClase09b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                frmClase09b dialog = new frmClase09b(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox C;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox cboFormaPago;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCambio;
    private javax.swing.JLabel lblCambioEnLetras;
    private javax.swing.JLabel lblCambioView;
    private javax.swing.JLabel lblCobrar;
    private javax.swing.JLabel lblCobrarView;
    private javax.swing.JLabel lblFormaPago;
    private javax.swing.JLabel lblFormaPago1;
    private javax.swing.JLabel lblRecibida;
    private javax.swing.JLabel lblReferencia;
    private javax.swing.JTextField txtRecibida;
    private javax.swing.JTextField txtReferencia;
    // End of variables declaration//GEN-END:variables
}
