import java.awt.Image;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;

public class frmClase04b extends javax.swing.JFrame {
    
    clsConnection oConn = new clsConnection();
    clsGlobales   oGlobal = new clsGlobales();

    /** Creates new form frmClase04b */
    public frmClase04b() {    /** Creates new form frmClase04b */

        initComponents();
        mnuReportes.setVisible(false);
        CSVReader.actualizarTablaProductos(oConn);
        // Maximiza la forma
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        //Carga la Imagen del Icono
        Image icon = new ImageIcon(getClass().getResource("jsw.png")).getImage();
        
        // Coloca la Imagen; no es necesario this
        this.setIconImage(icon);
        
        // Habilita Opciones de acuerdo al Role
        sbSubHabilitaOpciones();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        btnVender = new javax.swing.JButton();
        btnCalc = new javax.swing.JButton();
        btnVender1 = new javax.swing.JButton();
        btnVender2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mnuSistema = new javax.swing.JMenuBar();
        mnuProcesos = new javax.swing.JMenu();
        opcVentas = new javax.swing.JMenuItem();
        mnuCatalogos = new javax.swing.JMenu();
        opcProductos = new javax.swing.JMenuItem();
        mnuCalculadora = new javax.swing.JMenu();
        opcCalculadora = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        opcClientes = new javax.swing.JMenuItem();
        mnuPrincipal = new javax.swing.JMenu();
        opcProcesos = new javax.swing.JMenuItem();
        opcUsuarios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        opcParametros = new javax.swing.JMenuItem();
        opcRespRest = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        opcPuertoSerie = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        opcSalida = new javax.swing.JMenuItem();
        mnuReportes = new javax.swing.JMenu();
        opcReporteProcesos = new javax.swing.JMenuItem();
        opcReporteUsuarios = new javax.swing.JMenuItem();
        opcReporteVtasFPago = new javax.swing.JMenuItem();
        opcReporteVentas = new javax.swing.JMenuItem();
        opcReporteBitacora = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        opcClientes1 = new javax.swing.JMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");
        jCheckBoxMenuItem1.setName("jCheckBoxMenuItem1"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Pradera del Sur - Punto de Venta");
        setName("frmClase05"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setName("jPanel1"); // NOI18N

        btnVender.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnVender.setText("VENDER");
        btnVender.setName("btnVender"); // NOI18N
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        btnCalc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnCalc.setText("CALCULADORA");
        btnCalc.setName("btnCalc"); // NOI18N
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });

        btnVender1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnVender1.setText("PRODUCTOS");
        btnVender1.setName("btnVender1"); // NOI18N
        btnVender1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVender1ActionPerformed(evt);
            }
        });

        btnVender2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnVender2.setText("CLIENTES");
        btnVender2.setName("btnVender2"); // NOI18N
        btnVender2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVender2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVender, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVender2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVender1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVender, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVender2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVender1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo2.png"))); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        mnuSistema.setFont(new java.awt.Font("Lucida Sans", 0, 10)); // NOI18N
        mnuSistema.setName("mnuSistema"); // NOI18N

        mnuProcesos.setText("Ventas");
        mnuProcesos.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        mnuProcesos.setName("mnuProcesos"); // NOI18N

        opcVentas.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        opcVentas.setText("Vender");
        opcVentas.setName("opcVentas"); // NOI18N
        opcVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcVentasActionPerformed(evt);
            }
        });
        mnuProcesos.add(opcVentas);

        mnuSistema.add(mnuProcesos);

        mnuCatalogos.setText("Productos");
        mnuCatalogos.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        mnuCatalogos.setName("mnuCatalogos"); // NOI18N

        opcProductos.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        opcProductos.setText("Productos");
        opcProductos.setName("opcProductos"); // NOI18N
        opcProductos.setPreferredSize(new java.awt.Dimension(250, 25));
        opcProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opcProductosMousePressed(evt);
            }
        });
        opcProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcProductosActionPerformed(evt);
            }
        });
        mnuCatalogos.add(opcProductos);

        mnuSistema.add(mnuCatalogos);

        mnuCalculadora.setText("Calculadora");
        mnuCalculadora.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        mnuCalculadora.setName("mnuCalculadora"); // NOI18N

        opcCalculadora.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        opcCalculadora.setText("Calculadora ");
        opcCalculadora.setName("opcCalculadora"); // NOI18N
        opcCalculadora.setPreferredSize(new java.awt.Dimension(250, 25));
        opcCalculadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opcCalculadoraMousePressed(evt);
            }
        });
        opcCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcCalculadoraActionPerformed(evt);
            }
        });
        mnuCalculadora.add(opcCalculadora);

        mnuSistema.add(mnuCalculadora);

        jMenu1.setText("Clientes");
        jMenu1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jMenu1.setName("jMenu1"); // NOI18N

        opcClientes.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        opcClientes.setText("Clientes");
        opcClientes.setName("opcClientes"); // NOI18N
        opcClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcClientesActionPerformed(evt);
            }
        });
        jMenu1.add(opcClientes);

        mnuSistema.add(jMenu1);

        mnuPrincipal.setText("Configuracion");
        mnuPrincipal.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        mnuPrincipal.setName("mnuSistema"); // NOI18N

        opcProcesos.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        opcProcesos.setText("Procesos del Sistema");
        opcProcesos.setName("opcProcesos"); // NOI18N
        opcProcesos.setPreferredSize(new java.awt.Dimension(250, 25));
        opcProcesos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opcProcesosMousePressed(evt);
            }
        });
        opcProcesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcProcesosActionPerformed(evt);
            }
        });
        mnuPrincipal.add(opcProcesos);

        opcUsuarios.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        opcUsuarios.setText("Usuarios");
        opcUsuarios.setName("opcUsuarios"); // NOI18N
        opcUsuarios.setPreferredSize(new java.awt.Dimension(250, 25));
        opcUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opcUsuariosMousePressed(evt);
            }
        });
        opcUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcUsuariosActionPerformed(evt);
            }
        });
        mnuPrincipal.add(opcUsuarios);

        jSeparator1.setName("jSeparator1"); // NOI18N
        mnuPrincipal.add(jSeparator1);

        opcParametros.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        opcParametros.setText("Parametros");
        opcParametros.setName("opcParametros"); // NOI18N
        opcParametros.setPreferredSize(new java.awt.Dimension(250, 25));
        opcParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcParametrosActionPerformed(evt);
            }
        });
        mnuPrincipal.add(opcParametros);

        opcRespRest.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        opcRespRest.setText("Respaldar-Restaurar");
        opcRespRest.setName("opcRespRest"); // NOI18N
        opcRespRest.setPreferredSize(new java.awt.Dimension(250, 25));
        opcRespRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcRespRestActionPerformed(evt);
            }
        });
        mnuPrincipal.add(opcRespRest);

        jSeparator2.setName("jSeparator2"); // NOI18N
        mnuPrincipal.add(jSeparator2);

        jMenuItem2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jMenuItem2.setText("Listado de Art.");
        jMenuItem2.setName("jMenuItem2"); // NOI18N
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnuPrincipal.add(jMenuItem2);

        opcPuertoSerie.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        opcPuertoSerie.setText("Config. Envio de Mail");
        opcPuertoSerie.setName("opcPuertoSerie"); // NOI18N
        opcPuertoSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcPuertoSerieActionPerformed(evt);
            }
        });
        mnuPrincipal.add(opcPuertoSerie);

        jMenuItem1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jMenuItem1.setText("Puerto Serie Balanza");
        jMenuItem1.setName("jMenuItem1"); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuPrincipal.add(jMenuItem1);

        opcSalida.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        opcSalida.setText("Salida");
        opcSalida.setName("opcSalida"); // NOI18N
        opcSalida.setPreferredSize(new java.awt.Dimension(250, 25));
        opcSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opcSalidaMousePressed(evt);
            }
        });
        opcSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcSalidaActionPerformed(evt);
            }
        });
        mnuPrincipal.add(opcSalida);

        mnuSistema.add(mnuPrincipal);

        mnuReportes.setText("Reportes");
        mnuReportes.setEnabled(false);
        mnuReportes.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        mnuReportes.setName("mnuReportes"); // NOI18N

        opcReporteProcesos.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        opcReporteProcesos.setText("Procesos");
        opcReporteProcesos.setName("opcReporteProcesos"); // NOI18N
        opcReporteProcesos.setPreferredSize(new java.awt.Dimension(250, 25));
        opcReporteProcesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcReporteProcesosActionPerformed(evt);
            }
        });
        mnuReportes.add(opcReporteProcesos);

        opcReporteUsuarios.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        opcReporteUsuarios.setText("Usuarios");
        opcReporteUsuarios.setName("opcReporteUsuarios"); // NOI18N
        opcReporteUsuarios.setPreferredSize(new java.awt.Dimension(250, 25));
        opcReporteUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcReporteUsuariosActionPerformed(evt);
            }
        });
        mnuReportes.add(opcReporteUsuarios);

        opcReporteVtasFPago.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        opcReporteVtasFPago.setText("VtasXFormaPago");
        opcReporteVtasFPago.setName("opcReporteVtasFPago"); // NOI18N
        opcReporteVtasFPago.setPreferredSize(new java.awt.Dimension(250, 25));
        opcReporteVtasFPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcReporteVtasFPagoActionPerformed(evt);
            }
        });
        mnuReportes.add(opcReporteVtasFPago);

        opcReporteVentas.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        opcReporteVentas.setText("Ventas");
        opcReporteVentas.setName("opcReporteVentas"); // NOI18N
        opcReporteVentas.setPreferredSize(new java.awt.Dimension(250, 25));
        opcReporteVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcReporteVentasActionPerformed(evt);
            }
        });
        mnuReportes.add(opcReporteVentas);

        opcReporteBitacora.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        opcReporteBitacora.setText("Bitacora");
        opcReporteBitacora.setName("opcReporteBitacora"); // NOI18N
        opcReporteBitacora.setPreferredSize(new java.awt.Dimension(250, 25));
        opcReporteBitacora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcReporteBitacoraActionPerformed(evt);
            }
        });
        mnuReportes.add(opcReporteBitacora);

        mnuSistema.add(mnuReportes);

        jMenu2.setText("Reportes");
        jMenu2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jMenu2.setName("jMenu2"); // NOI18N

        opcClientes1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        opcClientes1.setText("Ventas");
        opcClientes1.setName("opcClientes1"); // NOI18N
        opcClientes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcClientes1ActionPerformed(evt);
            }
        });
        jMenu2.add(opcClientes1);

        mnuSistema.add(jMenu2);

        setJMenuBar(mnuSistema);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(838, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(21, 21, 21))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Habilita las opciones
    private void sbSubHabilitaOpciones()
    {
        // Habilita Deshablita opciones
        opcProcesos.setEnabled(fnBoolIsOptionEnabled("sis-pro-01"));
        opcUsuarios.setEnabled(fnBoolIsOptionEnabled("sis-usu-01"));
        opcParametros.setEnabled(fnBoolIsOptionEnabled("sis-par-01"));
        opcProductos.setEnabled(fnBoolIsOptionEnabled("cat-pro-01"));
       //.setEnabled(fnBoolIsOptionEnabled("pro-inv-01"));
        opcVentas.setEnabled(fnBoolIsOptionEnabled("pro-inv-02"));        
        opcReporteUsuarios.setEnabled(fnBoolIsOptionEnabled("rep-usu-01"));
        opcReporteProcesos.setEnabled(fnBoolIsOptionEnabled("rep-pro-01"));
        opcReporteVtasFPago.setEnabled(fnBoolIsOptionEnabled("rep-vta-01"));        
        opcReporteVentas.setEnabled(fnBoolIsOptionEnabled("rep-vta-02"));
        opcReporteBitacora.setEnabled(fnBoolIsOptionEnabled("rep-bit-01"));
        opcRespRest.setEnabled(fnBoolIsOptionEnabled("uti-res-01"));
    }
    // Habilita Opciones
    private boolean fnBoolIsOptionEnabled(String sOption)
    {
        String sStmt;
        boolean bResult=false;
        
        // Consulta para Verificar Acceso a Sistema-Procesos
        sStmt = " Select * from 03tblrolprocesos";
        sStmt+= " Where strRoleName='"+clsGlobales.sRole+"'";
        sStmt+= " And   strProcesoIde='"+sOption+"'";
        
        // Ejecuto el Query
        oConn.FnBoolQueryExecute(sStmt);
        try 
        {
            // Verifico que haya habido resultados
            if (oConn.setResult.next())        
               bResult=true;
        
            // Cierra la Consulta
            oConn.setResult.close();    
        } catch (SQLException ex) {
            Logger.getLogger(frmClase04b.class.getName()).log(Level.SEVERE, null, ex);
        }        
        
        // Retorna el Resultado
        return bResult;
        
    }
private void opcSalidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcSalidaMousePressed
    // TODO add your handling code here:
    
    // Mensaje de que no logrola conexioncontacto@enviro.cl

    int iResult;
    iResult =JOptionPane.showConfirmDialog(null,"¿Desea Salir del Sistema?","Confirma Salida",JOptionPane.YES_NO_OPTION);
    if (iResult==0)
    {
       // Cierra la Forma 
       this.dispose();        
    }
    
    
}//GEN-LAST:event_opcSalidaMousePressed

private void opcProcesosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcProcesosMousePressed
// TODO add your handling code here:

    // Verifica bitácora activa
    if (oGlobal.fnBoolBitacoraActiva())
       oGlobal.sbGrabaBitacora(clsGlobales.sSystemUser, "Ingreso Sistema Procesos");
    
    // Declaro la Variable de la Forma de Procesos
    frmClase05 frmProcesos = new frmClase05(this,true);
    
    // Muestra la Forma
    frmProcesos.setVisible(true);
    //JOptionPane.showMessageDialog(null, "mensaje");
}//GEN-LAST:event_opcProcesosMousePressed

private void opcUsuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcUsuariosMousePressed
// TODO add your handling code here:

        // Verifica bitácora activa
    if (oGlobal.fnBoolBitacoraActiva())
       oGlobal.sbGrabaBitacora(clsGlobales.sSystemUser, "Ingreso Sistema Usuarios");

    // Declaro la Variable de la Forma de Usuarios
    frmClase06 frmUsuarios = new frmClase06(this,true);
    
    // Muestra la Forma
    frmUsuarios.setVisible(true);
    //JOptionPane.showMessageDialog(null, "mensaje");
    
}//GEN-LAST:event_opcUsuariosMousePressed

    private void opcProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcProductosMousePressed
        // TODO add your handling code here:

        // Verifica bitácora activa
        if (oGlobal.fnBoolBitacoraActiva())
           oGlobal.sbGrabaBitacora(clsGlobales.sSystemUser, "Ingreso Catálogo de Productos");

        // Declaro la Variable de la Forma de Procesos
        frmClase07 frmProductos = new frmClase07(this, true);

        // Muestra la Forma
        frmProductos.setVisible(true);

    }//GEN-LAST:event_opcProductosMousePressed

    private void opcReporteUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcReporteUsuariosActionPerformed
        // TODO add your handling code here:   
        // Verifica bitácora activa
        if (oGlobal.fnBoolBitacoraActiva())
           oGlobal.sbGrabaBitacora(clsGlobales.sSystemUser, "Reporte de Usuarios");
        
        try 
        {
                JasperReport myReport = JasperCompileManager.compileReport("rptUsuarios.jrxml");
                JasperPrint myPrint = JasperFillManager.fillReport(myReport,null,clsConnection.oConnection);
                JasperViewer.viewReport(myPrint,false);
                
        } catch (JRException ex) {
                //oFunc.SubSistemaMensaje(ex.getMessage());
                Logger.getLogger(frmClase04b.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_opcReporteUsuariosActionPerformed

    private void opcReporteProcesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcReporteProcesosActionPerformed
       // TODO add your handling code here:
       // Verifica bitácora activa
        if (oGlobal.fnBoolBitacoraActiva())
           oGlobal.sbGrabaBitacora(clsGlobales.sSystemUser, "Reporte de Procesos");

       try 
       {
            // Carga el archivo jasper al objeto JasperReport
            //JasperReport myReport = (JasperReport) JRLoader.loadObjectFromLocation("rptProcesos.jasper");
            JasperReport myReport = JasperCompileManager.compileReport("rptProcesos.jrxml");
                //JasperPrint myPrint = JasperFillManager.fillReport(myReport,null,new JREmptyDataSource());
           
            // Genera el reporte usando el objeto JasperReport e indicando la conexion
            JasperPrint myPrint = JasperFillManager.fillReport(myReport,null,clsConnection.oConnection);
            //JasperPrint myPrint = JasperFillManager.fillReport(myReport, null,new JREmptyDataSource());
            
        //    JasperPrint myPrint = JasperFillManager.fillReport;
            
            
            // Visualiza el Reporte
            JasperViewer.viewReport(myPrint,false);
            
        } catch (JRException ex) {
            Logger.getLogger(frmClase04b.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_opcReporteProcesosActionPerformed

    private void opcReporteVtasFPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcReporteVtasFPagoActionPerformed
        // TODO add your handling code here:
        // Verifica bitácora activa
        if (oGlobal.fnBoolBitacoraActiva())
           oGlobal.sbGrabaBitacora(clsGlobales.sSystemUser, "Reporte de Ventas por Forma de Pago");
    
        // Declaro la Variable de la Forma de Procesos
        frmClase11 frmReporteXFormasDePago = new frmClase11(null,true);

        // Muestra la Forma
        frmReporteXFormasDePago.setVisible(true);
        
        // Verifica que no haya cancelado
        if (! clsGlobales.sFecha1.equals(""))
        {
                //Pasamos parametros al reporte Jasper. 
                Map parameters = new HashMap(); 

                // Coloco los valores en los parámetros
                parameters.put("Fecha1",clsGlobales.sFecha1);             
                parameters.put("Fecha2",clsGlobales.sFecha2); 

                try 
                {
                    // Carga el archivo jasper al objeto JasperReport
                   // JasperReport myReport = (JasperReport) JRLoader.loadObjectFromLocation("reporteVtaFormaPago.jasper");
                    JasperReport myReport = (JasperReport)JasperCompileManager.compileReport("reporteVtaFormaPago.jrxml");           

                    // Genera el reporte usando el objeto JasperReport e indicando la conexion
                    JasperPrint myPrint = JasperFillManager.fillReport(myReport,parameters,clsConnection.oConnection);
                    //JasperPrint myPrint = JasperFillManager.fillReport(myReport, null,new JREmptyDataSource());

                    // Visualiza el Reporte
                    JasperViewer.viewReport(myPrint,false);

                } catch (JRException ex) {
                    Logger.getLogger(frmClase04b.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
               
    }//GEN-LAST:event_opcReporteVtasFPagoActionPerformed

    private void opcReporteVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcReporteVentasActionPerformed
        // TODO add your handling code here:
        
        // Verifica bitácora activa
        if (oGlobal.fnBoolBitacoraActiva())
           oGlobal.sbGrabaBitacora(clsGlobales.sSystemUser, "Reporte de Ventas");

        // Declaro la Variable de la Forma de Procesos
        frmClase11 frmReporteVentas = new frmClase11(null,true);

        // Muestra la Forma
        frmReporteVentas.setTitle("Reporte de Ventas");
        frmReporteVentas.setVisible(true);
        
        // Verifica que no haya cancelado
        if (! clsGlobales.sFecha1.equals(""))
        {
                //Pasamos parametros al reporte Jasper. 
                Map parameters = new HashMap(); 

                // Coloco los valores en los parámetros
                parameters.put("Fecha1",clsGlobales.sFecha1);             
                parameters.put("Fecha2",clsGlobales.sFecha2); 

                try 
                {
                    // Carga el archivo jasper al objeto JasperReport
                    //JasperReport myReport = (JasperReport) JRLoader.loadObjectFromLocation("\rptVentas2.jasper");
                    JasperReport myReport = (JasperReport)JasperCompileManager.compileReport("rptVentas2.jrxml");

                    // Genera el reporte usando el objeto JasperReport e indicando la conexion
                    JasperPrint myPrint = JasperFillManager.fillReport(myReport,parameters,clsConnection.oConnection);
                    //JasperPrint myPrint = JasperFillManager.fillReport(myReport, null,new JREmptyDataSource());

                    // Visualiza el Reporte
                    JasperViewer.viewReport(myPrint,false);

                } catch (JRException ex) {
                    Logger.getLogger(frmClase04b.class.getName()).log(Level.SEVERE, null, ex);
                }
        }

    }//GEN-LAST:event_opcReporteVentasActionPerformed

    private void opcRespRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcRespRestActionPerformed
        // TODO add your handling code here:        
        
        // Verifica bitácora activa
        if (oGlobal.fnBoolBitacoraActiva())
           oGlobal.sbGrabaBitacora(clsGlobales.sSystemUser, "Utilería Respaldar - Restaurar");

        // Declaro la Variable de la Forma de Procesos
        frmClase13 frmRespRest = new frmClase13(null,true);

        // Muestra la Forma
        frmRespRest.setTitle("Respaldar - Restaurar Información");
        frmRespRest.setVisible(true);
    }//GEN-LAST:event_opcRespRestActionPerformed

    private void opcParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcParametrosActionPerformed
        // TODO add your handling code here:
        // Verifica bitácora activa
        if (oGlobal.fnBoolBitacoraActiva())
           oGlobal.sbGrabaBitacora(clsGlobales.sSystemUser, "Ingreso a Sistema Parámetros");

        // Declaro la Variable de la Forma de Procesos
        frmClase14 frmParametros = new frmClase14(this,true);
    
        // Muestra la Forma
        frmParametros.setVisible(true);
 
    }//GEN-LAST:event_opcParametrosActionPerformed

    private void opcReporteBitacoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcReporteBitacoraActionPerformed
        // TODO add your handling code here:
        
        // Verifica bitácora activa
        if (oGlobal.fnBoolBitacoraActiva())
           oGlobal.sbGrabaBitacora(clsGlobales.sSystemUser, "Reporte de Bitácora");

        String sQuery;
        
        // Declaro la Variable de la Forma de Procesos
        frmClase15 frmReporteBitacora = new frmClase15(null,true);

        // Muestra la Forma
        frmReporteBitacora.setTitle("Reporte de Bitacora");
        frmReporteBitacora.setVisible(true);
        
        // Verifica que no haya cancelado
        if (! clsGlobales.sUsuario.equals(""))
        {
                //Pasamos parametros al reporte Jasper. 
                Map parameters = new HashMap(); 
                
                // Construye el Query dependiendo de lo seleccionado
                if (clsGlobales.sUsuario.equals("All"))
                {
                    // Construyo el Query
                    sQuery = "Select nick, CONCAT(dia , ' ' , hora) as dia, ip from 11tblbitacora";
                    
                }
                else
                {
                    
                    // Construyo el Query con filtro de usuario
                    sQuery = "Select nick, CONCAT(dia , ' ' , hora) as dia, ip from 11tblbitacora";
                    sQuery = sQuery + " Where nick='"+clsGlobales.sUsuario+"'";              
                    
                }  
                
                // Construyo el query con el filtro del Usuario
                parameters.put("sQuery",sQuery); 
                   
                try 
                {
                    // Carga el archivo jasper al objeto JasperReport
                    //JasperReport myReport = (JasperReport) JRLoader.loadObjectFromLocation("\rptBitacora.jasper");
                    JasperReport myReport = (JasperReport)JasperCompileManager.compileReport("rptBitacora.jrxml");

                    // Genera el reporte usando el objeto JasperReport e indicando la conexion
                    JasperPrint myPrint = JasperFillManager.fillReport(myReport,parameters,clsConnection.oConnection);

                    // Visualiza el Reporte
                    JasperViewer.viewReport(myPrint,false);

                } catch (JRException ex) {
                    Logger.getLogger(frmClase04b.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
    }//GEN-LAST:event_opcReporteBitacoraActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void opcVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcVentasActionPerformed
        // TODO add your handling code here:
        // Verifica bitácora activa
        if (oGlobal.fnBoolBitacoraActiva()) {
            oGlobal.sbGrabaBitacora(clsGlobales.sSystemUser, "Ingreso a Ventas");
        }

        // Declaro la Variable de la Forma de Procesos
        frmClase09 frmVentas = new frmClase09(null, true);

        // Muestra la Forma
        frmVentas.setVisible(true);
    }//GEN-LAST:event_opcVentasActionPerformed

    private void opcUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcUsuariosActionPerformed

    private void opcCalculadoraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcCalculadoraMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcCalculadoraMousePressed

    private void opcCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcCalculadoraActionPerformed
        // TODO add your handling code here:        if (oGlobal.fnBoolBitacoraActiva())
        oGlobal.sbGrabaBitacora(clsGlobales.sSystemUser, "Ingreso a la Calculadora de Costos de Elaboracion");

        // Declaro la Variable de la Forma de Procesos
        frmClase16 frmCalculadora= new frmClase16(this, true);

        // Muestra la Forma
        frmCalculadora.setVisible(true);
    }//GEN-LAST:event_opcCalculadoraActionPerformed

    private void opcProcesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcProcesosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcProcesosActionPerformed

    private void opcProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcProductosActionPerformed

    private void opcSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcSalidaActionPerformed

    private void opcPuertoSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcPuertoSerieActionPerformed
        // TODO add your handling code here:
                // Verifica bitácora activa
        if (oGlobal.fnBoolBitacoraActiva())
           oGlobal.sbGrabaBitacora(clsGlobales.sSystemUser, "Ingreso a la configuracion de Envio de Mail");

        // Declaro la Variable de la Forma de Procesos
        frmClase19 frmConfigEnvioMail = new frmClase19(this,true);
    
        // Muestra la Forma
        frmConfigEnvioMail.setVisible(true);
    }//GEN-LAST:event_opcPuertoSerieActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int confirmed = JOptionPane.showConfirmDialog(null, "Desea salir del sistema?", "Salir", JOptionPane.YES_NO_OPTION);
        if (confirmed == JOptionPane.YES_OPTION) {
//       
            this.setVisible(false);
            

            Loading salida = new Loading();

            // Muestra la Forma
            salida.setVisible(true);

            if (oGlobal.fnBoolBitacoraActiva()) {
                oGlobal.sbGrabaBitacora(clsGlobales.sSystemUser, "Salida del Sistema");
            }

        } else {
            setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosing

    private void opcClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcClientesActionPerformed
        // TODO add your handling code here:
           if (oGlobal.fnBoolBitacoraActiva())
           oGlobal.sbGrabaBitacora(clsGlobales.sSystemUser, "Ingreso a la configuracion de Clientes");

        // Declaro la Variable de la Forma de Procesos
        frmClase20 frmClientes = new frmClase20(this,true);
    
        // Muestra la Forma
        frmClientes.setVisible(true);
    }//GEN-LAST:event_opcClientesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
                // TODO add your handling code here:
           if (oGlobal.fnBoolBitacoraActiva())
           oGlobal.sbGrabaBitacora(clsGlobales.sSystemUser, "Ingreso a la Configuracion de Puertos COM");

        // Declaro la Variable de la Forma de Procesos
        frmClase21 frmConfigPuerto = new frmClase21(this,true);
    
        // Muestra la Forma
        frmConfigPuerto.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        // TODO add your handling code here:
        // Verifica bitácora activa
        if (oGlobal.fnBoolBitacoraActiva()) {
            oGlobal.sbGrabaBitacora(clsGlobales.sSystemUser, "Ingreso a Ventas");
        }

        // Declaro la Variable de la Forma de Procesos
        frmClase09 frmVentas = new frmClase09(null, true);

        // Muestra la Forma
        frmVentas.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnVenderActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
                   if (oGlobal.fnBoolBitacoraActiva())
           oGlobal.sbGrabaBitacora(clsGlobales.sSystemUser, "Ingreso a la Configuracion del Listado de Precios");

        // Declaro la Variable de la Forma de Procesos
        frmClase22 frmConfigArchivoImportar = new frmClase22(this,true);
    
        // Muestra la Forma
        frmConfigArchivoImportar.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        // TODO add your handling code here:
        oGlobal.sbGrabaBitacora(clsGlobales.sSystemUser, "Ingreso a la Calculadora de Costos de Elaboracion");

        // Declaro la Variable de la Forma de Procesos
        frmClase16 frmCalculadora= new frmClase16(this, true);

        // Muestra la Forma
        frmCalculadora.setVisible(true);
    }//GEN-LAST:event_btnCalcActionPerformed

    private void btnVender1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVender1ActionPerformed
        // TODO add your handling code here:
        // Verifica bitácora activa
        if (oGlobal.fnBoolBitacoraActiva())
           oGlobal.sbGrabaBitacora(clsGlobales.sSystemUser, "Ingreso Catálogo de Productos");

        // Declaro la Variable de la Forma de Procesos
        frmClase07 frmProductos = new frmClase07(this, true);

        // Muestra la Forma
        frmProductos.setVisible(true);
    }//GEN-LAST:event_btnVender1ActionPerformed

    private void btnVender2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVender2ActionPerformed
        // TODO add your handling code here:
        if (oGlobal.fnBoolBitacoraActiva()) {
            oGlobal.sbGrabaBitacora(clsGlobales.sSystemUser, "Ingreso a la configuracion de Clientes");
        }

        // Declaro la Variable de la Forma de Procesos
        frmClase20 frmClientes = new frmClase20(this, true);

        // Muestra la Forma
        frmClientes.setVisible(true);
    }//GEN-LAST:event_btnVender2ActionPerformed

    private void opcClientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcClientes1ActionPerformed
        // TODO add your handling code here:
         if (oGlobal.fnBoolBitacoraActiva())
           oGlobal.sbGrabaBitacora(clsGlobales.sSystemUser, "Reporte de Ventas");

        // Declaro la Variable de la Forma de Procesos
        frmClase11 frmReporteVentas = new frmClase11(null,true);

        // Muestra la Forma
        frmReporteVentas.setTitle("Reporte de Ventas");
        frmReporteVentas.setVisible(true);
        
        // Verifica que no haya cancelado
        if (! clsGlobales.sFecha1.equals(""))
        {
                //Pasamos parametros al reporte Jasper. 
                Map parameters = new HashMap(); 

                // Coloco los valores en los parámetros
                parameters.put("Fecha1",clsGlobales.sFecha1);             
                parameters.put("Fecha2",clsGlobales.sFecha2); 

                try 
                {
                    // Carga el archivo jasper al objeto JasperReport
                    //JasperReport myReport = (JasperReport) JRLoader.loadObjectFromLocation("\rptVentas2.jasper");
                    JasperReport myReport = (JasperReport)JasperCompileManager.compileReport("rptVentasDesdeHasta.jrxml");

                    // Genera el reporte usando el objeto JasperReport e indicando la conexion
                    JasperPrint myPrint = JasperFillManager.fillReport(myReport,parameters,clsConnection.oConnection);
                    //JasperPrint myPrint = JasperFillManager.fillReport(myReport, null,new JREmptyDataSource());

                    // Visualiza el Reporte
                    JasperViewer.viewReport(myPrint,false);

                } catch (JRException ex) {
                    Logger.getLogger(frmClase04b.class.getName()).log(Level.SEVERE, null, ex);
                }
        }

    }//GEN-LAST:event_opcClientes1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmClase04b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmClase04b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmClase04b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmClase04b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmClase04b().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalc;
    private javax.swing.JButton btnVender;
    private javax.swing.JButton btnVender1;
    private javax.swing.JButton btnVender2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu mnuCalculadora;
    private javax.swing.JMenu mnuCatalogos;
    private javax.swing.JMenu mnuPrincipal;
    private javax.swing.JMenu mnuProcesos;
    private javax.swing.JMenu mnuReportes;
    private javax.swing.JMenuBar mnuSistema;
    private javax.swing.JMenuItem opcCalculadora;
    private javax.swing.JMenuItem opcClientes;
    private javax.swing.JMenuItem opcClientes1;
    private javax.swing.JMenuItem opcParametros;
    private javax.swing.JMenuItem opcProcesos;
    private javax.swing.JMenuItem opcProductos;
    private javax.swing.JMenuItem opcPuertoSerie;
    private javax.swing.JMenuItem opcReporteBitacora;
    private javax.swing.JMenuItem opcReporteProcesos;
    private javax.swing.JMenuItem opcReporteUsuarios;
    private javax.swing.JMenuItem opcReporteVentas;
    private javax.swing.JMenuItem opcReporteVtasFPago;
    private javax.swing.JMenuItem opcRespRest;
    private javax.swing.JMenuItem opcSalida;
    private javax.swing.JMenuItem opcUsuarios;
    private javax.swing.JMenuItem opcVentas;
    // End of variables declaration//GEN-END:variables
}
