
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @
 */
public class frmClase23 extends javax.swing.JDialog {

    /**
     * Creates new form frmClase07b
     */
    // Declaro variable de Conexion
    clsConnection oConn = new clsConnection();
    
    // Variable para las funciones propias
    clsFunciones  oFunc = new clsFunciones();
    
    
    
    public frmClase23(java.awt.Frame parent, boolean modal) 
    {
        // Código de Inicialización
        super(parent, modal);
        initComponents();
        
        //Centro la Forma   
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDetalle = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblMedida = new javax.swing.JLabel();
        lblInicial = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtCliente = new javax.swing.JTextField();
        txtDebe = new javax.swing.JTextField();
        txtAFavor = new javax.swing.JTextField();
        txtPrecio1 = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes");

        pnlDetalle.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cuenta Corriente Del Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 0, 12))); // NOI18N

        lblCodigo.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblCodigo.setText("Código:");

        lblNombre.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblNombre.setText("Cliente");

        lblDescripcion.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblDescripcion.setText("Saldo:");

        lblMedida.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblMedida.setText("Debe ultima compra:");

        lblInicial.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblInicial.setText("A Favor: (No se usa)");

        txtCodigo.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtCodigo.setMaximumSize(new java.awt.Dimension(170, 25));

        txtCliente.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtCliente.setMaximumSize(new java.awt.Dimension(170, 25));
        txtCliente.setPreferredSize(new java.awt.Dimension(170, 21));
        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });

        txtDebe.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtDebe.setMaximumSize(new java.awt.Dimension(170, 21));
        txtDebe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDebeActionPerformed(evt);
            }
        });

        txtAFavor.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtAFavor.setMaximumSize(new java.awt.Dimension(170, 21));
        txtAFavor.setPreferredSize(new java.awt.Dimension(170, 21));

        txtPrecio1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtPrecio1.setMaximumSize(new java.awt.Dimension(170, 21));
        txtPrecio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecio1ActionPerformed(evt);
            }
        });

        txtSaldo.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtSaldo.setMaximumSize(new java.awt.Dimension(170, 25));
        txtSaldo.setPreferredSize(new java.awt.Dimension(170, 21));
        txtSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDetalleLayout = new javax.swing.GroupLayout(pnlDetalle);
        pnlDetalle.setLayout(pnlDetalleLayout);
        pnlDetalleLayout.setHorizontalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCodigo)
                    .addComponent(lblNombre)
                    .addComponent(lblInicial)
                    .addComponent(lblDescripcion)
                    .addComponent(lblMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(txtDebe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPrecio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAFavor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pnlDetalleLayout.setVerticalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCodigo)
                    .addGroup(pnlDetalleLayout.createSequentialGroup()
                        .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDetalleLayout.createSequentialGroup()
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombre)))
                            .addComponent(txtPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescripcion))))
                .addGap(18, 18, 18)
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDebe, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedida, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAFavor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInicial))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btnAceptar.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aceptar.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(pnlDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
   
    
    public boolean fnBoolCteCteExiste(boolean bDisplay)
    {
        // Para devolver el resultado
        boolean bResultado=false;
        
        // Para el Query
        String sQuery;
        
        // Prepara el Query
        sQuery  = "Select * from 13tbldetallectacte Where intCtaCteCodigo="+txtCodigo.getText();
        
        //Ejecuta el Query
        oConn.FnBoolQueryExecute(sQuery);
        
        // Capturo el Error
        try {
            // Verifico que haya habido resultados
            if (oConn.setResult.next())
            {
        
                // Verifica si debe desplegar
                if (bDisplay)
                {
                    // Obtengo los datos
                    txtCodigo.setText(oConn.setResult.getString("intCtaCteCodigo"));
                    txtCliente.setText(oConn.setResult.getString("intClienteCodigo"));
                    txtSaldo.setText(oConn.setResult.getString("decSaldo"));
                    txtDebe.setText(oConn.setResult.getString("decDebe"));
                    txtAFavor.setText(oConn.setResult.getString("decAFavor"));


                }
                // Resultado
                bResultado = true;

            }
            
            // Cierro los Resultados
            oConn.setResult.close();
                
        } catch (SQLException ex) {
            oFunc.SubSistemaMensaje("Cuenta Corriente Existente:"+ex.getMessage().toString());
        }
        
        
        
        // Retorna el Resultado
        return bResultado;
        
    }
    
    // Procedimiento para insertar el producto
    private void sbInsertaCliente()
    {
       
        // Variable para la fecha
        Date dateHoy = new Date();
        // Variable para dar formato
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");

        
        String sQuery;
        
        // Prepara el Query para Insertar
        sQuery = "insert into 13tbldetallectacte values (";
        sQuery += txtCodigo.getText().toString()+",";
        sQuery += txtCliente.getText().toString()+",";
        sQuery += txtSaldo.getText().toString()+",";
        sQuery += txtDebe.getText().toString()+",";
        sQuery += txtAFavor.getText().toString()+",";
        sQuery += "'" + formato.format(dateHoy) + "')";
        
             
        // Ejecuta la Insercion
        if (oConn.FnBoolQueryExecuteUpdate(sQuery))
            oFunc.SubSistemaMensaje("La Inserción se ha realizado con éxito");
        
        // Cierra la Forma
        this.dispose();
        
    }
    
    private void sbModificaCtaCte()
    {
        
        Date dateHoy = new Date();
        // Variable para dar formato
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
        
        // Variable para el Queryformato.format(dateHoy)
        String sQuery;
               
        // Prepara el Query para Insertar
        sQuery = " Update 13tbldetallectacte Set ";
        sQuery += " intCtaCteCodigo="+txtCodigo.getText().toString()+",";
        sQuery += " intClienteCodigo="+txtCliente.getText().toString()+",";
        sQuery += " decDebe="+txtSaldo.getText()+",";
        sQuery += " decSaldo="+txtDebe.getText()+",";
        sQuery += " decAFavor="+txtAFavor.getText()+",";
        sQuery += " datFecha ='" + formato.format(dateHoy) + "'";
        sQuery += " Where intClienteCodigo= "+txtCodigo.getText();
        
        // Para ver el Query
        //oFunc.SubSistemaMensaje(sQuery);
                        
        // Ejecuta la Insercion
        if (oConn.FnBoolQueryExecuteUpdate(sQuery))
            oFunc.SubSistemaMensaje("La Modificación se ha realizado con éxito");
        
        // Cierra la Forma
        this.dispose();
        
    }
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        //if (this.getTitle().toString().lastIndexOf("Insertar") >= 0) {
            if (fnBoolCteCteExiste(true)) //oFunc.SubSistemaMensaje("El Código de Cuenta Corriente del Cliente ya existe");
            {
                sbModificaCtaCte();
            } else {
                sbInsertaCliente();
            }
        //}
        /*  else
            if (! fnBoolCteCteExiste(false))
              //  oFunc.SubSistemaMensaje("El Código de Cuenta Corriente del Cliente NO existe");
            //else
                   sbModificaCtaCte();
         */

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtDebeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDebeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDebeActionPerformed

    private void txtPrecio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecio1ActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void txtSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoActionPerformed

    
    
    // Setter para asiganar código
    public void setCodigo(String sCodigo)
    {
        // Coloco el Código
        txtCodigo.setText(sCodigo);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmClase07b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmClase07b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmClase07b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmClase07b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                frmClase23 dialog = new frmClase23(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblInicial;
    private javax.swing.JLabel lblMedida;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel pnlDetalle;
    private javax.swing.JTextField txtAFavor;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDebe;
    private javax.swing.JTextField txtPrecio1;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
