
import java.awt.Desktop;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;



/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @
 */
public class frmClase13 extends javax.swing.JDialog {

    /**
     * Creates new form frmClase13
     */
      // Variable para las funciones propias
    clsFunciones  oFunc = new clsFunciones();
    
    public frmClase13(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //Centro la Forma   
        this.setLocationRelativeTo(null);        
        this.setTitle("Reporte de Ventas por Forma de Pago");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblArchivo = new javax.swing.JLabel();
        txtArchivo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        atxtResultados = new javax.swing.JTextArea();
        Seleccionar = new javax.swing.JButton();
        rbRespaldar = new javax.swing.JRadioButton();
        rbRestaurar = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Respaldar Base de Datos");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnAceptar.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aceptar_venta.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setMaximumSize(new java.awt.Dimension(135, 57));
        btnAceptar.setMinimumSize(new java.awt.Dimension(135, 57));
        btnAceptar.setPreferredSize(new java.awt.Dimension(135, 57));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancelado_1.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblArchivo.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblArchivo.setText("Nombre del Archivo para ");

        txtArchivo.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        atxtResultados.setColumns(20);
        atxtResultados.setRows(5);
        jScrollPane1.setViewportView(atxtResultados);

        Seleccionar.setText("Seleccionar");
        Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarActionPerformed(evt);
            }
        });

        rbRespaldar.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        rbRespaldar.setSelected(true);
        rbRespaldar.setText("Respaldar");
        rbRespaldar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRespaldarActionPerformed(evt);
            }
        });

        rbRestaurar.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        rbRestaurar.setText("Restaurar");
        rbRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRestaurarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                        .addGap(45, 45, 45)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblArchivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbRespaldar))
                            .addComponent(txtArchivo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Seleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbRestaurar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArchivo)
                    .addComponent(rbRespaldar)
                    .addComponent(rbRestaurar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Seleccionar)
                    .addComponent(txtArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:

        String sCadena="";
        
        // Valida que haya algún nombre de archivo
        if (txtArchivo.getText().length()>7)
        {
            // Inicializa el area de texto
            atxtResultados.setText("");
            
            // Verifica acción a ejecutar
            if (rbRespaldar.isSelected())
            {
                // Ejecuta el Comando para crear el respaldo
                sbEjecutaComando("cmd /c respalda.bat "+ txtArchivo.getText().toString());
                
                try 
                {
                    BufferedReader bf = new BufferedReader(new FileReader(txtArchivo.getText().toString()));
                    try {
                        while ((sCadena = bf.readLine())!=null) 
                        {
                            //System.out.println(sCadena);
                            atxtResultados.setText(atxtResultados.getText()+sCadena+"\n");
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(frmClase13.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } 
                catch (FileNotFoundException ex) 
                {
                    Logger.getLogger(frmClase13.class.getName()).log(Level.SEVERE, null, ex);
                }    
            }
            else
            {
                /* Código para obtener el separdor de archivo del S.0.
                String so = System.getProperty("Windows");
                String separador = System.getProperty("file.separator");
                */ 
                /* Cödigo para abrir una seseión de msdos
                File consola = new File("restaura.bat");
                Desktop escritorio = Desktop.getDesktop();
                try {
                    escritorio.open(consola);
                    
                    try {
                        escritorio.wait();
                    } catch (InterruptedException ex) {
                        Logger.getLogger(frmClase13.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (IOException ex) {
                    Logger.getLogger(frmClase13.class.getName()).log(Level.SEVERE, null, ex);
                }
                */
                
                // Ejecuta el Comando para crear el respaldo
                sbEjecutaComando("cmd /c restaura.bat "+txtArchivo.getText().toString());
                
            }
                
        }
        else
            oFunc.SubSistemaMensaje("Debe Capturar el Nombre del Archivo mayor de 7 caracteres");
        
            
        
        

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void SbLoadInformation(String v)
    {
        //javax.swing.JOptionPane.showMessageDialog(null, v, "Avisador",javax.swing.JOptionPane.PLAIN_MESSAGE );
        
        atxtResultados.setText(atxtResultados.getText()+v+"\n");
    }
    // Ejecuta comando de respaldo
    private void sbEjecutaComando(String pcmd)
    {
        try
        {
            // Variable para Ejecutar el Proceso
            Process cmd = Runtime.getRuntime().exec(pcmd);
            
            // Espera a que termine el proceso
            cmd.waitFor();
            /*
            System.out.println(cmd.getOutputStream().toString());
            System.out.println(cmd.getInputStream().toString());
            System.out.println(cmd.getErrorStream().toString());
            */ 
            // Buffer para obtener la respuesta del Comando
            BufferedReader buf=new BufferedReader(new InputStreamReader(cmd.getInputStream()));
            String linea="";
            while ((linea=buf.readLine())!=null){
                System.out.println(linea);
                SbLoadInformation(linea.toString());
            } //fin while
            
            // Buffer para obtener la respuesta del Comando   
            BufferedReader buf2=new BufferedReader(new InputStreamReader(cmd.getErrorStream()));
            String linea2="";
            while ((linea2=buf2.readLine())!=null){
                System.out.println(linea2);
                SbLoadInformation(linea2.toString());
            } //fin while
            
        } //fin try
        catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(null, e, "Excepcion",javax.swing.JOptionPane.PLAIN_MESSAGE );
        }
    }
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        // Acepta la Venta
        clsGlobales.bVentaRealizada = false;

        // Cierra la Forma
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int iResult = fileChooser.showOpenDialog(null);
        if (iResult == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            txtArchivo.setText(file.toString());
        }
    }//GEN-LAST:event_SeleccionarActionPerformed

    private void rbRespaldarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRespaldarActionPerformed
        // TODO add your handling code here:
        rbRestaurar.setSelected(! rbRespaldar.isSelected());
    }//GEN-LAST:event_rbRespaldarActionPerformed

    private void rbRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRestaurarActionPerformed
        // TODO add your handling code here:
        rbRespaldar.setSelected(! rbRestaurar.isSelected());
    }//GEN-LAST:event_rbRestaurarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmClase13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmClase13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmClase13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmClase13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                frmClase13 dialog = new frmClase13(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Seleccionar;
    private javax.swing.JTextArea atxtResultados;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblArchivo;
    private javax.swing.JRadioButton rbRespaldar;
    private javax.swing.JRadioButton rbRestaurar;
    private javax.swing.JTextField txtArchivo;
    // End of variables declaration//GEN-END:variables
}
