
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmClase05.java
 *
 * Created on 11/11/2019, 09:29:15 AM
 */
/**
 *
 * @author jaor
 */
public class frmClase19 extends javax.swing.JDialog {

    // Declaro variable de Conexion
    clsConnection oConn = new clsConnection();
    
    /** Creates new form frmClase05 */
    public frmClase19(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // Centra la Forma
        this.setLocationRelativeTo(null);
        
            
        // Carga el ListBox con los procesos
        SubProcesosCarga();
        
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlProcesos = new javax.swing.JPanel();
        txtDestinatario = new javax.swing.JTextField();
        butGrabar = new javax.swing.JButton();
        txtRemitente = new javax.swing.JTextField();
        txtCopia = new javax.swing.JTextField();
        txtCopiaOculta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema-Procesos");

        pnlProcesos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Envio de Mail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 0, 12))); // NOI18N
        pnlProcesos.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        pnlProcesos.setName("pnlProcesos"); // NOI18N

        txtDestinatario.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtDestinatario.setName("txtDestinatario"); // NOI18N
        txtDestinatario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDestinatarioKeyPressed(evt);
            }
        });

        butGrabar.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        butGrabar.setText("Aceptar");
        butGrabar.setName("butGrabar"); // NOI18N
        butGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butGrabarActionPerformed(evt);
            }
        });

        txtRemitente.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtRemitente.setName("txtRemitente"); // NOI18N
        txtRemitente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRemitenteActionPerformed(evt);
            }
        });
        txtRemitente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRemitenteKeyPressed(evt);
            }
        });

        txtCopia.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtCopia.setName("txtCopia"); // NOI18N
        txtCopia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCopiaKeyPressed(evt);
            }
        });

        txtCopiaOculta.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtCopiaOculta.setName("txtCopiaOculta"); // NOI18N
        txtCopiaOculta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCopiaOcultaKeyPressed(evt);
            }
        });

        jLabel1.setText("Remitente:");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Destinatario:");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText("Copia:");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText("Copia Oculta:");
        jLabel4.setName("jLabel4"); // NOI18N

        javax.swing.GroupLayout pnlProcesosLayout = new javax.swing.GroupLayout(pnlProcesos);
        pnlProcesos.setLayout(pnlProcesosLayout);
        pnlProcesosLayout.setHorizontalGroup(
            pnlProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProcesosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(10, 10, 10)
                .addGroup(pnlProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDestinatario)
                    .addComponent(txtRemitente)
                    .addComponent(txtCopia)
                    .addComponent(txtCopiaOculta))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProcesosLayout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(butGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        pnlProcesosLayout.setVerticalGroup(
            pnlProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProcesosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRemitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(pnlProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(pnlProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCopia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(pnlProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCopiaOculta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(butGrabar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(pnlProcesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlProcesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlProcesos.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void txtRemitenteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRemitenteKeyPressed
// TODO add your handling code here:
    
}//GEN-LAST:event_txtRemitenteKeyPressed

private void txtDestinatarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDestinatarioKeyPressed
// TODO add your handling code here:
}//GEN-LAST:event_txtDestinatarioKeyPressed

private void butGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butGrabarActionPerformed

    // TODO add your handling code here:
    String strSqlStmt;
    
    
    // Valida los datos correctos
    if (FnBoolValidaDatos())
    {
        // Prepara el Query
        strSqlStmt  = " Update 14tblConfigMail ";
        strSqlStmt += " Set strRemitente='"+txtRemitente.getText()+"', ";
        strSqlStmt += " strDestinatario='"+txtDestinatario.getText()+"', ";
        strSqlStmt += " strCopia='"+txtCopia.getText()+"', ";
        strSqlStmt += " strCopiaOculta='"+txtCopiaOculta.getText()+"' ";

        // Ejecuta el Query
        oConn.FnBoolQueryExecuteUpdate(strSqlStmt);

        // Carga los Procesos de Nueva Cuenta
        
        this.dispose();
       // SubProcesosCarga();
    
    }
}//GEN-LAST:event_butGrabarActionPerformed

    private void txtCopiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCopiaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCopiaKeyPressed

    private void txtCopiaOcultaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCopiaOcultaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCopiaOcultaKeyPressed

    private void txtRemitenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRemitenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRemitenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmClase05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmClase05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmClase05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmClase05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                frmClase05 dialog = new frmClase05(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                
               
            }
        });
    }
   
    // Carga los Procesos existentes a la lista
    private void SubProcesosCarga()
    {
        // Para instrucción sql
        String sqlStmt;
        String strRemitente = "";
        String strDestinatario = "";
        String strCopia = "";
        String strCopiaOculta = "";
        
         // Prepara Variable para realizar el Query
        sqlStmt = "Select * from 14tblConfigMail";
        
        if (oConn.FnBoolQueryExecute(sqlStmt))
        {
            try 
            {
                // Verifica resultados
                 while (oConn.setResult.next())
                 {
                     // Obtiene los datos de la Consulta
                     strRemitente = oConn.setResult.getString ("strRemitente");
                     strDestinatario = oConn.setResult.getString ("strDestinatario");
                     strCopia = oConn.setResult.getString ("strCopia");
                     strCopiaOculta = oConn.setResult.getString ("strCopiaOculta");
                 }                 
                  
                 txtRemitente.setText(strRemitente);
                 txtDestinatario.setText(strDestinatario);
                 txtCopia.setText(strCopia);
                 txtCopiaOculta.setText(strCopiaOculta);
                 
                 
                 // Cierra Resultados
                 oConn.setResult.close();
            } 
            catch (SQLException ex) 
            {
                JOptionPane.showMessageDialog(rootPane,ex);
                Logger.getLogger(frmClase05.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }
    
    // Valida que los datos sean capturador
    boolean FnBoolValidaDatos()
    {
        // Variable para el Mensaje
        String strMensaje="";
        
        // Valida el Ide
        if (txtRemitente.getText().length()==0 )
        {
           strMensaje = "Debe completar el campo Remitente con el siguiente formato (ejemplo: nombre@gmail.com)";
           txtRemitente.requestFocus();
        }
        
        // Valida el Nombre
        if (txtDestinatario.getText().length()==0)
        {
           if (strMensaje.length()==0)
              txtDestinatario.requestFocus();
           strMensaje = strMensaje + "\n"+"Debe completar el campo Destinatario con el siguiente formato (ejemplo: nombre@email.com)";
          
        }
                
        // Valida si faltaron datos
        if (strMensaje.length()>0)
        {
            // Construye el Mensaje
            strMensaje ="Debe ingresar los siguientes datos:\n"+strMensaje;
            
            // Muestra el Mensaje
            JOptionPane.showMessageDialog(this, strMensaje);
            
            // Retorna
            return false;
            
        }
        else
            
            return true;
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butGrabar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel pnlProcesos;
    private javax.swing.JTextField txtCopia;
    private javax.swing.JTextField txtCopiaOculta;
    private javax.swing.JTextField txtDestinatario;
    private javax.swing.JTextField txtRemitente;
    // End of variables declaration//GEN-END:variables
}
